const facts = [
  ["Hühnerhaltung","leicht","Grundbedürfnisse von Hühnern","Hühner brauchen Scharrflächen, Ruheplätze und geschützte Rückzugsorte.","Ein gut gefüllter Futterplatz deckt auch den Beschäftigungsbedarf der Hühner.","Hühner ruhen bevorzugt auf offenen Flächen ohne seitliche Deckung.","Für Hühner ist eine glatte Bodenfläche günstiger als lockeres Scharrmaterial.","Eine gute Haltung berücksichtigt Nahrung, Bewegung, Ruhe, Sozialverhalten und Sicherheit."],
  ["Hühnerhaltung","mittel","Sozialverhalten","Hühner bilden innerhalb ihrer Gruppe eine soziale Rangordnung.","Hühner verteilen den Zugang zum Futter nach einem regelmäßigen Wechsel.","Hühner ordnen ihren Rang vorwiegend nach der Helligkeit des Gefieders.","Hühner lösen ihre sozialen Bindungen mit jeder nächtlichen Ruhephase auf.","Die sogenannte Hackordnung beeinflusst unter anderem Zugang zu Ressourcen und Ruheplätzen."],
  ["Zwerghühner","leicht","Zwerghühner","Zwerghühner benötigen trotz kleiner Körpergröße eine strukturierte Haltung und Beschäftigung.","Bei Zwerghühnern reicht die Futteraufnahme als tägliche Beschäftigung aus.","Bei Zwerghühnern entfällt durch das geringe Gewicht der Bedarf an Sitzplätzen.","Zwerghühner bevorzugen übersichtliche Buchten ohne Verstecke oder Deckung.","Körpergröße ändert nichts an den grundlegenden Ansprüchen an Platz, Beschäftigung und Pflege."],
  ["Zwerghühner","schwer","Ur- und verzwergte Rassen","Zwerghühner umfassen sowohl Urzwerge als auch verkleinerte Formen großer Rassen.","Urzwerge sind Jungtiere großer Hühnerrassen vor dem Erreichen ihres endgültigen Körpergewichts.","Verzwergte Rassen sind durch Futterbegrenzung klein gehaltene Großrassen.","Urzwerge entstehen durch Kreuzung zweier bereits verzwergter Großrassen.","In der Rassegeflügelzucht wird zwischen Urzwergen und verzwergten Großrassen unterschieden."],
  ["Puten","leicht","Putenhaltung","Puten brauchen trockene Einstreu, Frischluft und Bewegungsraum.","Für Puten ist leicht feuchte Einstreu zur Pflege der Fußsohlen günstig.","Puten profitieren nachts von geschlossen gehaltenen Lüftungsöffnungen.","Für Puten ersetzt eine höhere Stalltemperatur fehlenden Bewegungsraum.","Trockene Einstreu, saubere Luft und Platz sind wichtige Grundlagen der Putenhaltung."],
  ["Puten","mittel","Jungputen","Jungputen sind in der frühen Aufzucht gegenüber Nässe und Kälte empfindlich.","Jungputen gleichen Wärmeverluste vor allem durch enges Zusammenrücken aus.","Jungputen entwickeln ihre Kälteresistenz durch frühzeitige Zugluft im Stall.","Jungputen vertragen feuchte Böden schon kurz nach dem vollständigen Schlupf.","Wärme, Trockenheit und ein passend eingestelltes Stallklima sind in der frühen Aufzucht entscheidend."],
  ["Wassergeflügel","leicht","Wassergeflügel","Enten und Gänse brauchen Wasser, in das sie den ganzen Kopf eintauchen können.","Enten und Gänse reinigen ihre Nasen ausreichend an einer flachen Nippeltränke.","Für die Augenpflege genügt Wassergeflügel das Benetzen der Schnabelspitze.","Wassergeflügel hält die Nasenöffnungen vorwiegend durch Reiben am Gefieder frei.","Geeignete Wasserstellen unterstützen arttypische Pflege und freie Nasenöffnungen."],
  ["Wassergeflügel","mittel","Nasse Stallbereiche","Eine räumlich gut geplante Tränkenzone erleichtert das Reinigen und hält Ruheflächen trockener.","Tränken auf lockerer Nesteinstreu halten die übrige Stallfläche am besten trocken.","Tränken direkt neben den Nestern schützen das Nestmaterial vor Verunreinigung.","Feuchte Tränkenbereiche sollten mit trockener Einstreu überdeckt statt geräumt werden.","Eine durchdachte Tränkenzone erleichtert Hygiene und hält Ruheflächen trockener."],
  ["Enten","leicht","Entengefieder","Enten verteilen bei der Gefiederpflege das Sekret ihrer Bürzeldrüse.","Enten bilden das pflegende Gefiedersekret vorwiegend in der Schnabelhaut.","Enten verteilen bei der Gefiederpflege das Sekret ihrer Speicheldrüsen.","Enten nehmen das pflegende Gefiederfett hauptsächlich mit dem Badewasser auf.","Beim Putzen verteilen Vögel das Sekret der Bürzeldrüse im Gefieder."],
  ["Enten","mittel","Laufenten","Bei Laufenten fällt besonders die aufrechte Haltung ihres Körpers auf.","Laufenten zeigen eine waagerechte Haltung mit breit getragener Brust.","Laufenten fallen durch einen tief getragenen Rumpf und einen eher kurzen Hals auf.","Laufenten zeigen eine nach vorn abfallende Rückenlinie beim Stehen.","Die aufrechte Haltung gehört zu den typischen Merkmalen der Laufenten."],
  ["Gänse","leicht","Gänse als Weidetiere","Gänse nutzen Gras als Futter, brauchen aber eine ausgewogene Gesamtversorgung.","Eine dichte Grasweide deckt den Mineralstoffbedarf wachsender Gänse ohne Ergänzung.","Bei Gänsen verringert junges Weidegras den Bedarf an einer eigenen Trinkstelle.","Gänse verwerten überständiges, hartes Gras besser als junge, blattreiche Bestände.","Weidegang ist wertvoll, muss aber zu Alter, Jahreszeit und Gesamtversorgung passen."],
  ["Gänse","mittel","Gänseverhalten","Gänse kommunizieren durch deutliche Rufe und bewachen aufmerksam ihr Revier.","Gänse verständigen sich innerhalb der Gruppe vorwiegend durch Schnabelklappern.","Gänse reagieren auf fremde Tiere überwiegend mit einem leisen Lockruf.","Gänse nutzen laute Rufe hauptsächlich während der nächtlichen Ruhephase.","Ihre Wachsamkeit und Lautäußerungen sind bekannte Bestandteile des Gänseverhaltens."],
  ["Wachteln","leicht","Japanische Legewachteln","Japanische Legewachteln brauchen bodennahe Deckung und Rückzugsbereiche.","Japanische Legewachteln bevorzugen erhöhte Schlafplätze über der Deckung.","Japanische Legewachteln fühlen sich auf freien Flächen ohne Sichtbarrieren sicherer.","Japanische Legewachteln benötigen offene Nestflächen nahe der Tränke.","Struktur, Deckung und geeignete Bodenbereiche reduzieren Stress."],
  ["Wachteln","mittel","Schreckreaktion bei Wachteln","Bei Schreck können Wachteln steil auffliegen und gegen die Decke stoßen.","Bei Schreck fliegen Wachteln bevorzugt flach entlang der Volierenwände.","Eine niedrige harte Decke fängt den Schreckflug von Wachteln schonend ab.","Wachteln reagieren auf plötzliches Licht vorwiegend mit reglosem Verharren.","Eine angepasste Höhe oder nachgiebige Decke kann Verletzungen bei Schreckflügen vorbeugen."],
  ["Geflügelrassen","leicht","Rassenvielfalt","Rassen unterscheiden sich in Körperform, Leistung, Verhalten und Gefieder.","Die Rassezuordnung richtet sich vorrangig nach dem Alter beim ersten Ei.","Geflügel mit gleicher Gefiederfarbe wird derselben Rasse zugeordnet.","Unterschiede im Körperbau gelten innerhalb der Rassezuordnung als nachrangig.","Rassen entstanden durch unterschiedliche Nutzungsziele, Regionen und züchterische Auswahl."],
  ["Geflügelrassen","mittel","Zweinutzungsrassen","Zweinutzungsrassen wurden traditionell für Eier und für Fleisch gehalten.","Zweinutzungsrassen verbinden Naturbrut und künstliche Erbrütung.","Zweinutzungsrassen eignen sich zugleich für Stall- und Weidehaltung.","Zweinutzungsrassen werden nach zwei unterschiedlichen Farbschlägen gezüchtet.","Der Begriff beschreibt die Verbindung zweier klassischer Nutzungsrichtungen."],
  ["Brut","leicht","Brutdauer beim Haushuhn","Hühnereier benötigen bis zum Schlupf gewöhnlich rund drei Wochen.","Beim Haushuhn liegt die übliche Brutdauer bei etwa 18 Tagen.","Beim Haushuhn ist nach ungefähr 24 Tagen mit dem Schlupf zu rechnen.","Beim Haushuhn schlüpfen die Küken gewöhnlich nach rund 28 Tagen.","Etwa drei Wochen gelten beim Haushuhn als übliche Brutdauer, kleine Abweichungen sind möglich."],
  ["Brut","mittel","Bruteier lagern","Bruteier werden sauber, erschütterungsarm und möglichst kurz gelagert.","Bruteier lagert man günstig bei Bruttemperatur, um die Entwicklung vorzubereiten.","Bruteier gewinnen durch mehrwöchige Lagerung an gleichmäßiger Schlupffähigkeit.","Bruteier lagert man günstig nahe dem Gefrierpunkt, um die Keimscheibe zu schonen.","Lagerdauer und -bedingungen beeinflussen die Entwicklungs- und Schlupfchancen."],
  ["Kunstbrut","leicht","Wenden bei der Kunstbrut","Regelmäßiges Wenden unterstützt die Entwicklung und beugt ungünstigem Anhaften vor.","Das Wenden dient hauptsächlich dem Vergrößern der Luftkammer am stumpfen Eipol.","Regelmäßiges Wenden gleicht einen zu geringen Sauerstoffgehalt der Brutluft aus.","Das Wenden löst Kalzium aus der Schale und macht es dem Embryo direkt zugänglich.","Das Wenden verhindert unter anderem ein ungünstiges Anhaften des Embryos an den Eihäuten."],
  ["Kunstbrut","schwer","Schlupfphase","Kurz vor dem Schlupf endet das Wenden; das Brutklima wird für die Schlupfphase angepasst.","Zum Schlupf wird häufiger gewendet, damit das Küken leichter die Lage wechseln kann.","Zum Schlupf wird die Lüftung reduziert, um den Wärmeverlust der Eier zu begrenzen.","Zum Schlupf wird die Feuchte abgesenkt, damit die Schalenhäute rascher austrocknen.","Die letzten Bruttage unterscheiden sich organisatorisch von der vorherigen Entwicklungsphase."],
  ["Naturbrut","leicht","Glucke","Eine Glucke wärmt und wendet die Eier und führt nach dem Schlupf die Küken.","Eine Glucke beendet die Wärmezufuhr, sobald die Küken die Schalen anpicken.","Eine Glucke nimmt während der Brut mehr Futter auf, um ihre Eiablage fortzusetzen.","Eine Glucke beginnt mit dem regelmäßigen Wenden erst kurz vor dem Schlupftermin.","Brutverhalten umfasst Wärmen, Wenden, kurze Versorgungspausen und später die Kükenführung."],
  ["Naturbrut","mittel","Brutnest","Ein Brutnest soll trocken und geschützt liegen sowie für Kontrollen gut erreichbar sein.","Ein Brutnest im belebten Stallgang fördert die Gewöhnung an spätere Störungen.","Eine gemeinsame Nestnutzung synchronisiert das Nachlegen mit dem Brutbeginn.","Helles Licht über dem Brutnest erleichtert der Glucke die Pflege des Geleges.","Ein geschützter Bereich verringert Stress und erleichtert die Zuordnung des Geleges."],
  ["Kükenaufzucht","leicht","Wärmebedarf von Küken","Küken brauchen eine Wärmezone mit freiem Zugang zu kühleren Bereichen.","Küken brauchen eine gleichmäßig erwärmte Fläche ohne Temperaturgefälle.","Die Wärmezone sollte den gesamten Boden bis in die Ruhebereiche erfassen.","Die Wärmeversorgung richtet sich vorrangig nach der Raumtemperatur am Eingang.","Eine Temperaturzone erlaubt den Küken, ihren Aufenthaltsort selbst passend zu wählen."],
  ["Kükenaufzucht","mittel","Küken beobachten","Dicht gedrängte, laut piepsende Küken können frieren oder sich unwohl fühlen.","Dichtes Drängen mit lautem Piepsen ist typisch für eine gut passende Wärmezone.","Dicht gedrängte Küken geben durch das Piepsen überschüssige Körperwärme ab.","Lautes Piepsen in einem dichten Kükenhaufen zeigt vorwiegend beginnende Sättigung.","Verteilung, Aktivität und Lautäußerungen liefern Hinweise auf das Wohlbefinden."],
  ["Stallbau","leicht","Sitzstangen","Sitzstangen sollen sicheren Halt und einen gut erreichbaren Ruheplatz bieten.","Sitzstangen mit glatter Oberfläche verbessern das Greifen der Zehen.","Sitzstangen über der Tränke erleichtern die nächtliche Wasseraufnahme.","Sitzstangen dicht unter der Stalldecke ermöglichen einen besonders sicheren Abflug.","Form, Abstand und Position beeinflussen sicheren Auf- und Abstieg sowie Hygiene."],
  ["Stallbau","mittel","Legenester","Legenester sollten sauber, ruhig und leicht abgedunkelt sein.","Legenester werden unter einer hellen Lampe meist besonders gut angenommen.","Legenester im Laufweg erleichtern den Hennen eine ungestörte Eiablage.","Leicht angefeuchtete Nesteinstreu schützt Eier besser vor Verschmutzungen.","Geschützte Nester werden eher angenommen und helfen, Eier sauber zu halten."],
  ["Stallklima","leicht","Lüftung","Gute Lüftung führt Feuchte und Schadgase ab, ohne Zugluft auf die Tiere zu richten.","Lüftung sollte den stärksten Luftstrom unmittelbar auf die Sitzplätze richten.","Bei kühlem Wetter sollten Lüftungsöffnungen zugunsten der Wärme geschlossen bleiben.","Ammoniakgeruch zeigt an, dass der Luftwechsel für einen warmen Stall ausreichend ist.","Frische Luft und kontrollierter Luftaustausch gehören zu einem gesunden Stallklima."],
  ["Stallklima","mittel","Feuchtigkeit im Stall","Kondenswasser und feuchte Einstreu können auf zu wenig Luftaustausch hindeuten.","Beschlagene Flächen sprechen für eine besonders wirksame Abfuhr der Stallfeuchte.","Feuchte Einstreu bindet Keime dauerhaft und senkt dadurch den Infektionsdruck.","Kondenswasser bildet sich bevorzugt an den wärmsten Flächen im Stallinneren.","Feuchte Bedingungen fördern Gerüche, Keime und Probleme an Füßen und Gefieder."],
  ["Stallhygiene","leicht","Einstreu","Nasse oder verschmutzte Einstreu wird bei der Stallpflege entfernt und trocken ersetzt.","Feuchte Einstreu wird durch Andrücken verdichtet, damit sie schneller abtrocknet.","Eine frische Deckschicht über nasser Einstreu verhindert die Bildung unerwünschter Schadgase.","Kotansammlungen unter Sitzstangen dienen als trocknende Grundlage frischer Einstreu.","Trockene, gepflegte Einstreu trägt zu Fußgesundheit und Luftqualität bei."],
  ["Stallhygiene","mittel","Reinigungsreihenfolge","Vor der Desinfektion werden Schmutz und organische Reste entfernt.","Desinfiziert wird vor der Reinigung, damit sich der Schmutz leichter ablösen lässt.","Organische Reste verstärken die Wirkung des Mittels und können liegen bleiben.","Die mechanische Reinigung folgt nach Ablauf der Einwirkzeit des Desinfektionsmittels.","Organisches Material kann die Wirkung vieler Desinfektionsmittel deutlich verringern."],
  ["Fütterung","leicht","Alleinfutter","Alleinfutter ist auf den Nährstoffbedarf einer bestimmten Tiergruppe abgestimmt.","Alleinfutter braucht zur Bedarfsdeckung eine gleich große Portion Getreidekörner.","Alleinfutter für Legehennen eignet sich wegen des Mineralgehalts gut als Kükenstarter.","Alleinfutter bezeichnet eine Mischung aus Körnern ohne ergänzte Mineralstoffe.","Küken, Jungtiere und Legetiere haben unterschiedliche Anforderungen an die Ration."],
  ["Fütterung","mittel","Körner als Ergänzung","Zu viele Körner können das Nährstoffverhältnis eines Alleinfutters verschieben.","Mehr Körner gleichen einen niedrigen Aminosäurengehalt im Legefutter zuverlässig aus.","Eine hohe Körnergabe erhöht den Kalziumanteil einer Ration für legende Hennen.","Körner können eine Hälfte des Alleinfutters ersetzen, ohne die Nährstoffdichte zu ändern.","Zu viele Ergänzungen können das Verhältnis von Eiweiß, Energie, Vitaminen und Mineralstoffen verschieben."],
  ["Tränken","leicht","Frisches Trinkwasser","Geflügel braucht frei verfügbares Wasser für Verdauung und Temperaturregulation.","Zwei feste Tränkzeiten pro Tag decken den Wasserbedarf legender Hennen ab.","Feuchtes Grünfutter kann bei Weidehaltung eine separate Tränke ersetzen.","Leicht verschmutztes Wasser fördert eine günstige Gewöhnung an Stallkeime.","Wasser ist für Verdauung, Temperaturregulation, Leistung und Gesundheit unverzichtbar."],
  ["Tränken","mittel","Tränkenhöhe","Eine tiergerechte Tränkenhöhe begrenzt Verschmutzung und unnötigen Wasserverlust.","Die Tränkenhöhe richtet sich vorrangig nach der Höhe der vorhandenen Sitzstangen.","Eine tiefe Position in der Einstreu schützt den Tränkenrand vor eingetragenem Kot.","Eine Höhe über dem gestreckten Kopf vermindert den Wasserverlust beim Trinken.","Die geeignete Höhe orientiert sich an Tiergröße und Tränkensystem."],
  ["Mineralstoffe","leicht","Kalzium","Kalzium trägt zum Knochenaufbau und zur Eierschalenbildung bei.","Kalzium dient vorwiegend dem Aufbau sauerstoffbindender roter Blutzellen.","Kalzium wird bei Legehennen hauptsächlich für die Dotterpigmente gebraucht.","Kalzium deckt den wesentlichen Energiebedarf während der täglichen Eiablage.","Der Kalziumbedarf steigt besonders im Zusammenhang mit der Eischalenbildung."],
  ["Mineralstoffe","schwer","Grit und Muschelschalen","Magenkiesel helfen beim Zerkleinern von Futter; Muschelschalen liefern Kalzium.","Muschelschalen zerkleinern Futter; Magenkiesel liefern verwertbares Kalzium.","Magenkiesel liefern Spurenelemente; Muschelschalen liefern vorwiegend Phosphor.","Muschelschalen versorgen die Darmflora; Magenkiesel liefern lösliche Mineralstoffe.","Unlöslicher Grit und lösliche Kalziumquellen erfüllen unterschiedliche Aufgaben."],
  ["Geflügelgesundheit","leicht","Tägliche Tierkontrolle","Tägliche Kontrollen helfen, Abweichungen bei Verhalten, Futter und Kot zu erkennen.","Eine wöchentliche Kontrolle reicht aus, sofern am Monatsende das Gewicht stimmt.","Die Kontrolle der Futtermenge ersetzt die Beobachtung einzelner Tiere im Bestand.","Die Kontrolle ruhender Tiere liefert mehr Hinweise als Beobachtungen bei Aktivität.","Frühe Abweichungen sind oft leichter zu erkennen, wenn der normale Bestand gut bekannt ist."],
  ["Geflügelgesundheit","mittel","Quarantäne","Neue Tiere werden vor der Eingliederung eine Zeit lang getrennt vom Bestand beobachtet.","Neue Tiere werden zur Beobachtung in eine Nachbarbucht mit gemeinsamer Tränke gesetzt.","Ein gemeinsamer Auslauf während der Quarantäne erleichtert die Erregerkontrolle.","Die Quarantäne endet sinnvollerweise nach der ersten unauffälligen Futteraufnahme.","Ein getrennter Bereich reduziert das Risiko, unbemerkte Erreger oder Parasiten einzuschleppen."],
  ["Parasiten","leicht","Ektoparasiten","Ektoparasiten besiedeln die Körperoberfläche oder das direkte Tierumfeld.","Ektoparasiten entwickeln sich im Darm und werden mit dem Kot ausgeschieden.","Ektoparasiten leben in inneren Organen und ernähren sich vom Wirtsgewebe.","Ektoparasiten werden über Bruteier übertragen und besiedeln die Dottermembran.","Milben und Federlinge gehören zu bekannten äußeren Parasiten."],
  ["Parasiten","mittel","Bestandskontrolle auf Parasiten","Bei der Parasitenkontrolle sind Gefieder, Ritzen und Sitzstangenauflagen zu prüfen.","Eine Gefiederkontrolle zur Mittagszeit erfasst auch versteckt lebende Stallmilben.","Die Kontrolle sauberer Laufflächen reicht zur Einschätzung des Milbenbefalls aus.","Parasitenkontrollen konzentrieren sich auf die frisch gereinigten Futteroberflächen.","Einige Parasiten verstecken sich tagsüber in Spalten und werden leicht übersehen."],
  ["Milben","leicht","Rote Vogelmilbe","Rote Vogelmilben verstecken sich oft in Ritzen und saugen vorwiegend nachts Blut.","Rote Vogelmilben bleiben zwischen Blutmahlzeiten vorwiegend an den Federkielen sitzen.","Rote Vogelmilben befallen vor allem die Beinbeschuppung und graben dort ihre Gänge.","Rote Vogelmilben halten sich tagsüber zur Blutaufnahme bevorzugt auf dem Huhn auf.","Ihre versteckte Lebensweise macht Kontrollen an Sitzplätzen und Ritzen besonders wichtig."],
  ["Milben","schwer","Milbenbekämpfung","Milbenbekämpfung berücksichtigt Verstecke, Entwicklungsstadien und zugelassene Mittel.","Eine Behandlung am Tier erreicht auch die abgelegten Milbeneier in Stallritzen.","Nach dem Entfernen sichtbarer Milben können Kontrollen bis zur nächsten Mauser warten.","Ein Mittelwechsel nach jeder Anwendung macht die Beachtung der Einwirkzeit entbehrlich.","Wiederholte Kontrolle und ein abgestimmtes Vorgehen sind wegen des Lebenszyklus wichtig."],
  ["Würmer","leicht","Endoparasiten","Würmer können je nach Art den Verdauungstrakt oder andere Organe des Geflügels belasten.","Ein innerer Wurmbefall lässt sich am Tier vorwiegend an den typischen Fraßspuren im Federkleid erkennen.","Bei innerem Wurmbefall liegen die erwachsenen Parasiten regelmäßig offen im Kot.","Ein Befall des Verdauungstrakts steigert die Aufnahme von Nährstoffen aus dem Futter.","Je nach Art und Befallsstärke können Leistung, Gewicht und Allgemeinzustand leiden."],
  ["Würmer","mittel","Kotuntersuchung","Befunde aus Kotuntersuchungen können gezielte Maßnahmen gegen einen Wurmbefall begründen.","Eine einzelne negative Kotprobe schließt auch einen sehr frischen Wurmbefall aus.","Die Menge sichtbarer Futterreste erlaubt eine genaue Bestimmung der Wurmart.","Ein unauffälliger Kotgeruch spricht gegen die Notwendigkeit einer Parasitenuntersuchung.","Diagnostik hilft, Behandlungen fachlich zu begründen und unnötigen Einsatz zu vermeiden."],
  ["Krankheiten","leicht","Kranke Tiere separieren","Auffällige Tiere werden unter Beachtung der Biosicherheit getrennt und fachlich beurteilt.","Auffällige Tiere werden zur Erholung in eine bestehende Jungtiergruppe umgesetzt.","Eine offene Nachbarbucht mit gemeinsamem Futtertrog genügt als hygienische Trennung.","Nach einer einzelnen normalen Mahlzeit kann ein auffälliges Tier wieder in seine Gruppe zurückgesetzt werden.","Eine vorübergehende Trennung erleichtert Beobachtung und kann Kontakte reduzieren."],
  ["Krankheiten","mittel","Antibiotika","Antibiotika wirken gegen bestimmte Bakterien; gegen Viren sind sie unwirksam.","Antibiotika hemmen die Vermehrung von Viren, sofern sie früh gegeben werden.","Antibiotika verkürzen bei viralen Infektionen gezielt die Phase der Virusausscheidung.","Antibiotika ersetzen bei bakteriellen Infektionen die körpereigene Immunantwort.","Diagnose, tierärztliche Anweisung und verantwortungsvoller Einsatz sind entscheidend."],
  ["Newcastle-Krankheit","leicht","Newcastle-Krankheit","Newcastle ist eine ansteckende Viruserkrankung des Geflügels.","Newcastle ist eine bakterielle Erkrankung der Atemwege beim Geflügel.","Newcastle ist eine durch Einzeller verursachte Darmerkrankung beim Geflügel.","Newcastle ist eine Pilzerkrankung nach Aufnahme belasteter Einstreu.","Die Krankheit kann sich zwischen Beständen verbreiten und erfordert konsequente Vorsorge."],
  ["Newcastle-Krankheit","mittel","Newcastle-Vorsorge","Planmäßiger Aufbau und Auffrischung des Impfschutzes gehören zur Newcastle-Vorsorge.","Die Newcastle-Vorsorge stützt sich auf vorbeugende Antibiotikagaben vor dem Zukauf.","Eine frühere Impfung macht weitere Auffrischungen für die Bestandsvorsorge entbehrlich.","Die Newcastle-Vorsorge kann auf Impfungen verzichten, wenn der Stall sauber wirkt.","Ein planmäßig aufgebauter und aufgefrischter Impfschutz reduziert das Erkrankungsrisiko."],
  ["Impfungen","leicht","Impfschutz","Impfungen bereiten die spezifische Immunabwehr auf den Kontakt mit bestimmten Erregern vor.","Impfungen beseitigen vorhandene Erreger im Körper unmittelbar durch eine direkte Abtötung im Blut.","Impfungen übertragen eine dauerhaft unveränderte Menge fertiger Abwehrstoffe.","Impfungen ersetzen die Entwicklung einer eigenen Immunantwort nach Erregerkontakt.","Die Immunantwort benötigt Zeit und muss je nach Impfstoff wieder aufgefrischt werden."],
  ["Impfungen","mittel","Impfstoffhandhabung","Lagerung, Vorbereitung und Anwendung richten sich nach den Impfstoffvorgaben.","Geöffnete Impfstoffreste lassen sich bis zum Folgetermin im Kühlschrank aufbewahren.","Eine höhere Lagertemperatur verbessert die Verteilung eines Lebendimpfstoffs im Wasser.","Eine doppelte Dosis gleicht eine zu lange Lagerung nach dem Anmischen aus.","Temperatur, Zeit und Anwendung beeinflussen die Qualität einer Impfung."],
  ["Biosicherheit","leicht","Saubere Stallkleidung","Stalleigene Schuhe und Kleidung helfen, die Verschleppung von Krankheitserregern zu begrenzen.","Ein trockener Schuhwechsel macht die Reinigung gemeinsam benutzter Geräte entbehrlich.","Sauber aussehende Alltagsschuhe können ohne zusätzlichen Schuhwechsel in verschiedene Ställe getragen werden.","Stallkleidung wird zur Keimreduktion zwischen benachbarten Beständen gemeinsam genutzt.","Organisches Material an Schuhen und Geräten kann Krankheitserreger weitertragen."],
  ["Biosicherheit","mittel","Besucher und Geräte","Tierkontakte, Besucher und gemeinsam genutzte Geräte sind Teil des Hygienekonzepts.","Gemeinsame Geräte bleiben im Hygienekonzept unberücksichtigt, wenn kein Kot anhaftet.","Besucher benötigen bei kurzen Stallbesuchen keine betriebseigene Schutzkleidung.","Hygienemaßnahmen für Geräte beschränken sich auf deren erste Anschaffung.","Kontrollierte Wege und gereinigte Ausrüstung verringern mögliche Eintragswege."],
  ["Tierkennzeichnung","leicht","Kennzeichnung","Eindeutige Kennzeichnung hilft, Tiere und ihre Zuchtinformationen nachvollziehbar zuzuordnen.","Eine Kennzeichnung am Tier dokumentiert seine Erbanlagen genauer als der geführte Abstammungsnachweis.","Eine gemeinsame Farbmarkierung genügt zur individuellen Zuordnung aller Geschwister.","Eine Kennzeichnung erlaubt die sichere Rassebestimmung unabhängig von Zuchtunterlagen.","Zuordnung ist für Abstammung, Alter, Zuchtplanung und Bestandsführung hilfreich."],
  ["Tierkennzeichnung","mittel","Ringe kontrollieren","Fußringe müssen passen und auf ihren Sitz kontrolliert werden.","Fußringe sollen am erwachsenen Tier fest gegen die Beinhaut anliegen.","Fußringe werden nach dem Anlegen vorwiegend auf ihre Farbwirkung geprüft.","Fußringe gleicher Weite passen bei allen Rassen desselben Schlupfjahrgangs.","Wachstum, Verschmutzung oder Verletzungen können Probleme verursachen."],
  ["Bundesringe","leicht","Geschlossene Bundesringe","Geschlossene Ringe werden im geeigneten Jungtieralter über den Fuß gestreift.","Geschlossene Ringe werden erst nach der Geschlechtsreife über den Fuß geschoben.","Geschlossene Ringe lassen sich zum Anlegen an einer vorgesehenen Naht öffnen.","Geschlossene Ringe werden bei der ersten Ausstellung an das Bein angepresst.","Nach dem Wachstum lässt sich ein passender geschlossener Ring nicht zerstörungsfrei abnehmen."],
  ["Bundesringe","schwer","Informationen auf Bundesringen","Der Bundesring erlaubt die Zuordnung anhand seines Jahrgangs und der individuellen Nummer.","Bundesringe tragen das genaue Schlupfdatum und das aktuelle Gewicht des Tieres.","Bundesringe weisen die Elterntiere und deren letzte Ausstellungsergebnisse aus.","Bundesringe dokumentieren den Impfstatus und den Zeitpunkt der letzten Untersuchung.","Die Ringangaben unterstützen die Identifikation, müssen aber mit Zuchtaufzeichnungen verbunden werden."],
  ["Rassegeflügelzucht","leicht","Zuchtziel","Ein Zuchtziel berücksichtigt rassetypische Merkmale ebenso wie Gesundheit und Vitalität.","Ein Zuchtziel richtet die Auswahl vorrangig auf die höchste erreichbare Körpermasse.","Ein Zuchtziel wird für jede einzelne Brut nach den zufällig vorhandenen Tieren festgelegt.","Ein Zuchtziel ersetzt die Prüfung der Gesundheit durch die Bewertung des Erscheinungsbilds.","Verantwortungsvolle Auswahl achtet auf Funktion, Typ und robuste Nachzucht."],
  ["Rassegeflügelzucht","mittel","Zuchtbuch","Das Zuchtbuch hält Abstammung, Schlupf, Leistung und Beobachtungen fest.","Das Zuchtbuch enthält vorrangig die Rangfolge der Tiere am gemeinsamen Futterplatz.","Das Zuchtbuch ersetzt individuelle Tiernummern durch eine Sammelangabe je Stall.","Das Zuchtbuch wird erst für Tiere begonnen, die eine Ausstellung gewonnen haben.","Systematische Daten verbessern Nachvollziehbarkeit und Paarungsplanung."],
  ["Vererbung","leicht","Gene","Bei der Fortpflanzung geben beide Elternteile Erbanlagen an ihre gemeinsamen Nachkommen weiter.","Die Erbanlagen einer Tochter stammen überwiegend vom gleichgeschlechtlichen Elternteil.","Die Erbanlagen für die Körperform stammen beim Huhn aus dem mütterlichen Erbgut.","Der Vater vererbt die sichtbaren Merkmale, die Mutter die verdeckten Anlagen.","Die sichtbare Ausprägung entsteht aus Erbanlagen und Umwelteinflüssen."],
  ["Vererbung","schwer","Rezessive Merkmale","Rezessive Anlagen können verdeckt getragen und bei passender Kombination sichtbar werden.","Rezessive Anlagen verschwinden nach einer Generation ohne sichtbare Merkmalsausprägung.","Rezessive Anlagen setzen sich im mischerbigen Zustand gegenüber dominanten Anlagen durch.","Rezessive Anlagen werden bei der Befruchtung bevorzugt aus den Keimzellen entfernt.","Trägertiere können eine Anlage weitergeben, ohne sie selbst sichtbar zu zeigen."],
  ["Farben","mittel","Gefiederfarben","Gefiederfarben werden durch genetisch gesteuerte Pigmente und Strukturwirkungen bestimmt.","Die Farbe des Gefieders wird vorwiegend durch die Schalenfarbe des Bruteis festgelegt.","Die Färbung neuer Federn richtet sich hauptsächlich nach der täglichen Lichtdauer.","Die Gefiederfarbe wird bei der ersten Mauser unabhängig von den Erbanlagen neu festgelegt.","Mehrere Gene können Grundfarbe, Zeichnung, Verdünnung und Glanz beeinflussen."],
  ["Farben","schwer","Farbvererbung","Manche Farbmerkmale liegen auf Geschlechtschromosomen und werden geschlechtsgebunden vererbt.","Geschlechtsgebundene Farben werden von Hennen an ihre Töchter direkt weitergegeben.","Reziproke Kreuzungen liefern bei geschlechtsgebundener Farbvererbung übereinstimmende Nachkommen.","Geschlechtsgebundene Farbmerkmale liegen beim Huhn auf denselben Genorten wie die Eigröße.","Die Lage eines Gens auf einem Geschlechtschromosom kann Paarungsergebnisse beeinflussen."],
  ["Zuchtziele","leicht","Gesunde Zuchttiere","Gesunde, vitale und fortpflanzungsfähige Tiere bilden die Grundlage einer langfristig tragfähigen Zucht.","Eine hohe Bewertung der Körperform gleicht eingeschränkte Fruchtbarkeit bei Zuchttieren aus.","Die Auswahl gesunder Zuchttiere kann sich auf eine saubere Gefiederoberfläche beschränken.","Tiere mit schwacher Kondition sind zur Zucht geeignet, wenn ihre Farbe besonders typisch ist.","Äußere Merkmale dürfen nicht losgelöst von Gesundheit und Funktion betrachtet werden."],
  ["Zuchtziele","mittel","Auswahl über Generationen","Planmäßige Auswahl und Aufzeichnungen ermöglichen Fortschritt über Generationen.","Ein Wechsel des Zuchtziels nach jeder Brut beschleunigt die Festigung gewünschter Merkmale.","Die Auswahl nach dem höchsten Einzelgewicht ersetzt die Kontrolle verwandter Tiere.","Eine zufällige Verpaarung hält gewünschte Merkmale beständiger als eine geplante Auswahl.","Vererbung zeigt sich in Familien und Nachzucht, nicht nur im Erscheinungsbild eines Einzeltieres."],
  ["Ausstellungen","leicht","Ausstellungsvorbereitung","Gesunde und saubere Ausstellungstiere werden ruhig an Handhabung und Transport gewöhnt.","Ausstellungstiere werden zur Beruhigung unmittelbar vor dem Transport reichlich gefüttert.","Ausstellungstiere werden durch ungewohnte Gruppen am Vortag auf die Schau vorbereitet.","Ausstellungstiere sollten zur Gewöhnung längere Zeit in der geschlossenen Kiste bleiben.","Gesundheit, Pflege und stressarme Gewöhnung sind wichtiger als kurzfristige Kosmetik."],
  ["Ausstellungen","mittel","Transport zur Ausstellung","Eine geeignete Transportkiste bietet zur Tiergröße passenden Raum, Belüftung und einen sicheren Verschluss.","Eine eng bemessene Kiste verhindert Verletzungen besser als eine passende Transportgröße.","Abgedeckte Lüftungsöffnungen halten Ausstellungstiere während der Fahrt ausreichend ruhig.","Ein gemeinsam belegtes Fach eignet sich besonders zur sicheren Beförderung fremder Hähne.","Sichere Behälter schützen Tiere, Menschen und andere Verkehrsteilnehmer."],
  ["Bewertung","leicht","Rassegeflügelbewertung","Die Merkmale des ausgestellten Tieres werden mit dem geltenden Rassestandard verglichen.","Bei der Bewertung entscheidet vorwiegend die Legeleistung gegenüber anderen Schautieren.","Bei der Bewertung gilt das schwerste Tier einer Klasse als Maßstab für die übrigen Tiere.","Bei der Bewertung wird der Standard an die häufigsten Merkmale der ausgestellten Gruppe angepasst.","Typ, Form, Haltung, Gefieder und weitere Merkmale werden rassespezifisch betrachtet."],
  ["Bewertung","mittel","Bewertungskarte","Bewertungskarten dokumentieren die Vorzüge, Wünsche und festgestellten Mängel eines Tieres.","Die Bewertungskarte bescheinigt die Abstammung und den Inzuchtgrad des ausgestellten Tieres.","Die Bewertungskarte bestätigt den Gesundheitsstatus und die Befunde der letzten Kotprobe.","Die Bewertungskarte dokumentiert die Zuchtleistung und die Merkmale sämtlicher Nachkommen.","Die Hinweise können Züchterinnen und Züchtern bei der weiteren Auswahl helfen."],
  ["Vereinswesen","leicht","Geflügelzuchtverein","Vereine fördern den Erfahrungsaustausch und gemeinsame Aktivitäten der Mitglieder.","Vereine stellen die amtlichen Gesundheitsbescheinigungen für Ausstellungstiere aus.","Vereine legen die verbindlichen tierärztlichen Behandlungspläne ihrer Mitglieder fest.","Vereine führen die behördliche Registrierung sämtlicher Geflügelbestände durch.","Gemeinschaftliche Organisation unterstützt Zucht, Tiergesundheit und Nachwuchsarbeit."],
  ["Vereinswesen","mittel","Ehrenamt","Viele Angebote im Geflügelzuchtverein werden durch die ehrenamtliche Arbeit der Mitglieder ermöglicht.","Die fachliche Betreuung im Verein erfolgt vorrangig durch staatlich besoldete Zuchtwarte.","Die Organisation örtlicher Schauen wird überwiegend von amtlichen Tierärzten übernommen.","Die laufende Vereinsarbeit wird aus den Gebühren für verpflichtende Beratungen finanziert.","Zeit, Fachwissen und verlässliche Zusammenarbeit machen Vereinsangebote möglich."],
  ["Geschichte der Geflügelzucht","mittel","Domestikation des Haushuhns","Das Haushuhn geht in seiner Abstammung wesentlich auf das Bankivahuhn zurück.","Das Haushuhn geht vorwiegend auf das aus Indien stammende Graue Kammhuhn zurück.","Das Haushuhn stammt überwiegend vom Ceylon-Kammhuhn aus Sri Lanka ab.","Das Haushuhn geht im Wesentlichen auf das Grüne Kammhuhn aus Java zurück.","Über lange Zeit entstanden aus domestizierten Hühnern zahlreiche regionale Rassen und Schläge."],
  ["Geschichte der Geflügelzucht","schwer","Entstehung von Rassen","Regionale Bedingungen und verschiedene Nutzungsziele haben die Entwicklung vieler Rassen geprägt.","Die heutige Rassenvielfalt entstand vorwiegend durch Aufteilung nach Schlupfmonaten.","Rasseunterschiede entstanden überwiegend durch vorübergehende Fütterungsumstellungen.","Die meisten Rassen entstanden durch reine Standortwechsel ohne züchterische Auswahl.","Selektion auf Eier, Fleisch, Robustheit oder Erscheinungsbild formte die heutige Vielfalt."],
  ["Allgemeines Geflügelwissen","leicht","Muskelmagen","Der Muskelmagen zerkleinert die aufgenommene Nahrung durch mechanische Arbeit.","Der Muskelmagen übernimmt die saure Vorverdauung durch seine Drüsenzellen.","Der Muskelmagen speichert aufgenommene Körner vor der eigentlichen Verdauung.","Der Muskelmagen nimmt den größten Teil der gelösten Nährstoffe ins Blut auf.","Magenkiesel können die Zerkleinerung harter Futterbestandteile unterstützen."],
  ["Allgemeines Geflügelwissen","mittel","Kloake","Bei Vögeln münden Verdauungs-, Harn- und Geschlechtswege gemeinsam in die Kloake.","Die Kloake verbindet den Verdauungstrakt mit den Atemwegen und den Luftsäcken.","In die Kloake münden Darm und Legedarm; der Harn verlässt den Körper getrennt.","Die Kloake verbindet die Harnwege mit dem Darm, während Eier separat abgelegt werden.","Die Kloake ist eine gemeinsame Körperöffnung mit mehreren Funktionen."],
  ["Allgemeines Geflügelwissen","leicht","Staubbad","Staubbäder dienen der Gefiederpflege und dem arttypischen Verhalten.","Staubbäder versorgen das Gefieder mit den für die Federbildung benötigten Mineralien.","Staubbäder dienen vorwiegend dem Abkühlen der Eier vor dem täglichen Legebeginn.","Staubbäder ersetzen die Gefiederpflege mit dem Schnabel nach der Nahrungsaufnahme.","Trockene, lockere Substrate ermöglichen das typische Baden und Putzen."],
  ["Allgemeines Geflügelwissen","mittel","Mauser","Bei der Mauser wird altes Gefieder ersetzt; die Legeleistung kann dabei zeitweise sinken.","Die Mauser erneuert das Gefieder, ohne den Nährstoffbedarf der Henne zu verändern.","Die Mauser erneuert das Gefieder und löst dabei eine anhaltend höhere Eiablage aus.","Die Mauser erneuert das Gefieder vorwiegend durch Verlängerung vorhandener Federkiele.","Federneubildung benötigt Nährstoffe und kann den Organismus sichtbar beanspruchen."]
]

const advancedFacts = [
  ["Brutbiologie","schwer","Luftkammer und Schlupf","Die Luftkammer wächst durch Wasserverlust und dient dem Küken beim inneren Anpicken als erste Luftreserve.","Durch den Abbau des Dotters wächst die Luftkammer; sie übernimmt früh den Gasaustausch der Schalenporen.","Durch Flüssigkeitsaufnahme wächst die Luftkammer; ihre Größe zeigt den Fortschritt der Dotterresorption.","Durch Luftzufuhr über den spitzen Pol wächst die Luftkammer; das Küken nutzt sie erst nach dem äußeren Anpicken.","Ihre Entwicklung erlaubt Rückschlüsse auf den Feuchtigkeitsverlust; vor dem äußeren Schlupf nutzt das Küken die Luft in der Kammer."],
  ["Kunstbrut","schwer","Gewichtsverlust von Bruteiern","Der Gewichtsverlauf einer Eierstichprobe hilft, den Wasserverlust und damit die Feuchteführung zu beurteilen.","Der Gewichtsverlauf einer Eierstichprobe zeigt vorwiegend den Dotterverbrauch und damit die Energieversorgung.","Der Gewichtsverlauf einer Eierstichprobe dient zur Bestimmung der Befruchtungsrate vor dem ersten Schieren.","Der Gewichtsverlauf einer Eierstichprobe misst die Kalkauflösung und erlaubt Rückschlüsse auf das Skelettwachstum.","Wasser diffundiert durch die Schale; ein plausibler Verlauf hilft, Abweichungen der Feuchteführung zu erkennen."],
  ["Kunstbrut","schwer","Temperaturmessung im Brüter","Ein Messwert hängt davon ab, wo und auf welcher Höhe gemessen wird und wie der Brüter die Luft führt.","Ein am Boden platzierter Fühler bildet die Temperatur auf Embryohöhe durch den Temperaturausgleich gut ab.","Für Flächenbrüter ist der Messwert an der Decke als Temperatur auf Höhe der Eieroberseite zu verwenden.","Bei Umluftbrütern zeigt der Messwert direkt am Heizelement die mittlere Temperatur aller eingelegten Eier.","Temperaturschichtung und Luftbewegung machen eine zur Bauart passende Messposition erforderlich."],
  ["Bruteier","schwer","Porosität der Eischale","Durch Schalenporen diffundieren Sauerstoff, Kohlendioxid und Wasserdampf zwischen Ei und Umgebung.","Schalenporen führen Sauerstoff ins Ei; Kohlendioxid wird während der Brut vorwiegend im Eiklar gebunden.","Schalenporen transportieren gelöstes Kalzium zum Embryo und regulieren dabei den pH-Wert des Eiklars.","Schalenporen übernehmen die Atmung nach dem inneren Anpicken; zuvor erfolgt sie über die Dottermembran.","Der Embryo ist auf Diffusion durch Schale und Schalenhäute angewiesen; zugleich beeinflusst die Porosität den Wasserverlust."],
  ["Bruteier","schwer","Hagelschnüre","Die Hagelschnüre stabilisieren den Dotter im umgebenden Eiklar und halten die Keimscheibe in günstiger Lage.","Hagelschnüre führen Sauerstoff aus der Luftkammer zum Dotter und versorgen die Keimscheibe während der Frühbrut.","Hagelschnüre verbinden Dotter und Schalenhaut fest miteinander und verhindern dadurch das Drehen des Dotters.","Hagelschnüre bilden das erste Gefäßnetz und transportieren Nährstoffe zwischen Dotter und wachsendem Embryo.","Die spiraligen Eiweißstrukturen wirken als elastische Aufhängung des Dotters."],
  ["Kükenaufzucht","schwer","Beurteilung der Wärmezone","Kükenverhalten und Verteilung zeigen zusammen mit Messwerten, ob die Wärmezone passend eingestellt ist.","Ein mittiger Raumfühler bildet die empfundene Wärme genauer ab als die Verteilung der Küken unter dem Strahler.","Gleichmäßiges Meiden des Strahlers zeigt einen Bedarf an zusätzlicher Wärme und spricht für mehr Heizleistung.","Lautes Drängen unter dem Strahler spricht für einen zu großen Wärmebereich und erfordert weniger Heizleistung.","Zugluft, Bodenwärme und Strahlungsbereich können das Empfinden verändern; deshalb wird der Messwert mit Tierbeobachtung kombiniert."],
  ["Fütterung","schwer","Rohprotein und Aminosäuren","Der Rohproteingehalt allein zeigt nicht, ob verdauliche essenzielle Aminosäuren bedarfsgerecht vorhanden sind.","Bei gleichem Rohproteingehalt liefern unterschiedliche Futterproteine vergleichbare Mengen essenzieller Aminosäuren.","Fehlende essenzielle Aminosäuren werden bei hohem Rohproteingehalt durch Umwandlung von Rohfaser ausgeglichen.","Eine hohe Rohproteinaufnahme gleicht ein knappes Angebot an Methionin durch zusätzliche Energiegewinnung aus.","Entscheidend sind Verdaulichkeit und Aminosäurenmuster; limitierende Aminosäuren können die Nutzung des übrigen Proteins begrenzen."],
  ["Fütterung","schwer","Kalziumversorgung von Legehennen","Grobe Kalziumquellen bleiben länger im Muskelmagen und können so die nächtliche Schalenbildung unterstützen.","Fein vermahlenes Kalzium wird im Muskelmagen länger zurückgehalten und versorgt so die nächtliche Schalenbildung.","Eine hohe Kalziumaufnahme am Morgen verhindert die Aufnahme weiterer Kalziumteilchen während der Dunkelphase.","Grobe Kalziumteilchen werden rascher ausgeschieden und dienen daher vorwiegend der Versorgung am Vormittag.","Korngröße, Aufnahmezeit und Gesamtversorgung beeinflussen die Verfügbarkeit während der Schalenbildung."],
  ["Fütterung","schwer","Nicht-Stärke-Polysaccharide","Lösliche Nicht-Stärke-Polysaccharide können den Darminhalt zähflüssiger machen und die Nährstoffnutzung verändern.","Lösliche Nicht-Stärke-Polysaccharide senken die Viskosität des Darminhalts und beschleunigen dadurch den Enzymkontakt.","Lösliche Nicht-Stärke-Polysaccharide werden wie Stärke gespalten und stehen direkt als Glukose zur Aufnahme bereit.","Lösliche Nicht-Stärke-Polysaccharide erhöhen die Viskosität und verbessern dadurch die Durchmischung mit Enzymen.","Je nach Getreideart und Ration können viskose Faserfraktionen Verdauung und Kotbeschaffenheit verändern."],
  ["Verdauung","schwer","Funktion der Blinddärme","In den paarigen Blinddärmen werden bestimmte Futtersubstrate durch Mikroorganismen fermentiert.","Die Blinddärme dienen der Speicherung von Gallensaft und geben diesen portionsweise in den Dünndarm ab.","Die Blinddärme liefern die Hauptmenge der Verdauungsenzyme und spalten damit die Stärke der aufgenommenen Körner.","Die Blinddärme führen aufgenommene Magenkiesel zurück und regulieren so die Zerkleinerung im Muskelmagen.","Die Caeca beherbergen Mikroorganismen und tragen zur Fermentation bestimmter Substrate bei."],
  ["Stallklima","schwer","Ammoniak im Stall","Mikrobieller Abbau stickstoffhaltiger Ausscheidungen setzt Ammoniak frei; Feuchte, Temperatur und pH wirken mit.","Ammoniak entsteht vorwiegend beim Abbau von Kohlenhydraten in der Einstreu; der Stickstoffgehalt ist nachrangig.","Ammoniak entsteht durch Reaktion von ausgeatmetem Kohlendioxid mit Wasser; die Lüftung steuert diesen Prozess.","Ammoniak entsteht vorwiegend durch Zerfall mineralischer Einstreubestandteile; Mikroorganismen binden das Gas.","Feuchte Einstreu und ungünstige Lüftung fördern die Belastung; Schleimhäute und Atemwege können beeinträchtigt werden."],
  ["Stallklima","schwer","Relative Luftfeuchte","Die relative Luftfeuchte gibt den Sättigungsgrad an und verändert sich bei gleicher Dampfmenge mit der Temperatur.","Die relative Luftfeuchte gibt die Wassermasse je Kubikmeter an und bleibt beim Erwärmen unverändert erhalten.","Die relative Luftfeuchte beschreibt das Verhältnis von Kohlendioxid zu Wasserdampf und steigt mit dem Tierbesatz.","Die relative Luftfeuchte beschreibt den Taupunkt in Prozent und sinkt beim Abkühlen ohne zusätzliche Wasserzufuhr.","Wird Luft abgekühlt, kann die relative Feuchte bis zum Taupunkt steigen, obwohl keine Feuchte hinzugekommen ist."],
  ["Biosicherheit","schwer","Rein-Raus-Prinzip","Tiergruppen werden gemeinsam eingestallt; vor der nächsten Gruppe wird der geräumte Bereich gereinigt und desinfiziert.","Einzelne Tiere werden fortlaufend ersetzt; nach jedem Austausch wird der freie Stallplatz gereinigt und desinfiziert.","Tiergruppen wechseln täglich zwischen zwei belegten Bereichen; die jeweils freie Fläche wird trocken nachgestreut.","Ältere Tiere werden schrittweise durch Jungtiere ergänzt; nach Abschluss der Umstellung wird der Stall desinfiziert.","Das Unterbrechen von Infektionsketten gelingt besser, wenn Altersgruppen nicht fortlaufend vermischt und Bereiche gruppenweise aufbereitet werden."],
  ["Biosicherheit","schwer","Desinfektionswirksamkeit","Wirksamkeit setzt Reinigung voraus und hängt von Konzentration, Einwirkzeit, Temperatur und organischer Belastung ab.","Die Desinfektionswirkung lässt sich bei kalten Flächen durch eine entsprechend kürzere Einwirkzeit ausgleichen.","Die Desinfektionswirkung steigt bei organischen Belägen, weil das Mittel durch deren Bindung länger am Ort bleibt.","Die Desinfektionswirkung bleibt bei halber Konzentration erhalten, wenn die Einwirkzeit im gleichen Verhältnis sinkt.","Desinfektion setzt Reinigung und die Einhaltung der produktspezifischen Anwendungsbedingungen voraus."],
  ["Impfungen","schwer","Trinkwasserimpfung","Die Abstimmung von Impfstofflösung, Leitungen und Wasseraufnahme soll die nötige Dosis im vorgesehenen Zeitfenster sichern.","Die Tränkeleitungen sollten während der Impfstoffgabe weiter desinfiziert werden, damit der Lebendimpfstoff stabil bleibt.","Eine möglichst lange Verteilung der Impfstofflösung über mehrere Tage verbessert die gleichmäßige Dosisaufnahme.","Die Dosis wird auf die Wassermenge abgestimmt; Unterschiede in der Wasseraufnahme gleichen sich bei der Impfung aus.","Wasserqualität, Stabilisierung, Verteilung und zügige Aufnahme sind für eine gleichmäßige Immunisierung entscheidend."],
  ["Impfungen","schwer","Maternale Antikörper","Antikörper aus dem Muttertier schützen eine Zeit lang, können aber auch die Antwort auf bestimmte Impfstoffe beeinflussen.","Maternale Antikörper vermehren sich im Küken nach dem Schlupf und passen ihre Menge an dessen Körpergewicht an.","Maternale Antikörper werden durch die erste aktive Impfung aufgebaut und anschließend vom Küken im Dotter gespeichert.","Maternale Antikörper verstärken bei Lebendimpfstoffen die Vermehrung des Impfvirus und verkürzen so den Impfaufbau.","Die Antikörperspiegel fallen nach dem Schlupf ab; Impfzeitpunkt und Impfstoff müssen zur jeweiligen Situation passen."],
  ["Newcastle-Krankheit","schwer","Impfschutz und Infektion","Impfungen können Erkrankung und Ausscheidung deutlich mindern; eine sterile Immunität ist damit nicht sicher gewährleistet.","Die Impfung verhindert bei klinisch gesunden Tieren die Virusaufnahme, auch wenn sie einer hohen Dosis ausgesetzt sind.","Die Impfung entfernt bereits aufgenommenes Feldvirus durch direkte Konkurrenz, bevor die Immunantwort aufgebaut ist.","Die Impfung stellt nach einmaliger Aufnahme eine von der Anwendung unabhängige Barriere gegen die Virusausscheidung her.","Impfschutz, Expositionsdosis, Impfstoffanwendung und Immunstatus beeinflussen den Verlauf; Biosicherheit bleibt erforderlich."],
  ["Geflügelgesundheit","schwer","Bestandsdiagnostik","Für Bestandsdiagnosen sind Verlauf, Tiergruppe, klinische Befunde, Sektion und geeignete Laborproben zusammen wichtig.","Eine einzelne Kotfarbe erlaubt die Zuordnung der Erregergruppe genauer als Verlauf und Befunde der betroffenen Tiere.","Ein Laborbefund lässt sich ohne Entnahmezeit und Lagerbedingungen bewerten, wenn das Probengefäß beschriftet wurde.","Die Sektion eines Tieres ersetzt die Erhebung der Bestandsdaten, sofern dabei eine Organveränderung festgestellt wird.","Viele Geflügelkrankheiten zeigen ähnliche Symptome; Kontext und fachgerechte Proben erhöhen die diagnostische Sicherheit."],
  ["Parasiten","schwer","Präpatenzzeit bei Endoparasiten","Präpatenz ist die Zeit von der Infektion bis zum ersten nachweisbaren Auftreten von Fortpflanzungsprodukten des Parasiten.","Präpatenz ist die Zeit vom Beginn der Eiausscheidung bis zur ersten sichtbaren Beeinträchtigung des befallenen Tieres.","Präpatenz ist die Zeit vom Verlassen des Wirtes bis zum Erreichen des infektiösen Stadiums in der Stallumgebung.","Präpatenz ist die Zeit von der Aufnahme eines Parasiten bis zum ersten Auftreten klinischer Symptome beim Wirt.","Ein Tier kann bereits infiziert sein, obwohl beispielsweise noch keine Eier im Kot nachweisbar sind."],
  ["Kokzidien","schwer","Wirtsspezifität von Eimerien","Viele Eimeria-Arten des Huhns sind wirtsspezifisch und besiedeln bevorzugt bestimmte Darmabschnitte.","Die Eimerien des Huhns befallen dieselben Darmabschnitte; der Läsionsort zeigt vorwiegend das Alter des Wirtes an.","Die Eimerien des Huhns durchlaufen ihre Vermehrung in der Einstreu; im Darm erfolgt die Aufnahme der Nährstoffe.","Viele Eimerien des Huhns wechseln im Entwicklungszyklus zwischen Geflügel und einem pflanzenfressenden Zwischenwirt.","Art, Läsionsort und Entwicklungszyklus stehen in engem Zusammenhang und unterstützen die Einordnung eines Befalls."],
  ["Milben","schwer","Rote Vogelmilbe und Lebenszyklus","Die Rote Vogelmilbe lebt oft versteckt in Ritzen; zur Bekämpfung gehören diese Orte und ihre verschiedenen Entwicklungsstadien.","Viele Rote Vogelmilben legen ihre Eier an Federkielen ab; eine Behandlung des Gefieders erfasst daher den Hauptbefall.","Viele Rote Vogelmilben ruhen tagsüber auf dem Wirt; die Kontrolle der Tiere bei Helligkeit bildet den Stallbefall gut ab.","Viele Rote Vogelmilben verlassen den Stall nach der Blutmahlzeit; der Schwerpunkt liegt deshalb auf der Auslaufbehandlung.","Umgebung, Verstecke, Wiederholung und zugelassene Maßnahmen müssen in ein abgestimmtes Konzept einbezogen werden."],
  ["Genetik","schwer","Testpaarung","Eine Paarung mit einem homozygot rezessiven Tier kann verdeckte rezessive Anlagen eines dominant erscheinenden Tieres zeigen.","Eine Paarung mit einem homozygot dominanten Tier zeigt verdeckte rezessive Anlagen an den dominanten Nachkommen.","Eine Paarung zweier dominant erscheinender Tiere beweist deren Reinerbigkeit, wenn der erste Nachkomme dominant erscheint.","Eine Paarung mit einem homozygot rezessiven Tier verändert die rezessiven Anlagen des dominant erscheinenden Elternteils.","Bei Paarung mit einem passend homozygot rezessiven Tier können rezessive Nachkommen auf einen heterozygoten Elternteil hinweisen."],
  ["Genetik","schwer","Unvollständige Dominanz","Bei unvollständiger Dominanz zeigt der heterozygote Phänotyp eine Zwischenform gegenüber den beiden homozygoten Phänotypen.","Bei unvollständiger Dominanz gleicht die heterozygote Ausprägung der dominanten Form, während die rezessive verdeckt bleibt.","Bei unvollständiger Dominanz werden beide elterlichen Ausprägungen im heterozygoten Tier getrennt und vollständig sichtbar.","Bei unvollständiger Dominanz bestimmt das Geschlecht des heterozygoten Tieres, welches Allel als dominantes ausgeprägt wird.","Die Ausprägung erlaubt häufig eine phänotypische Unterscheidung aller drei Genotypklassen."],
  ["Genetik","schwer","Geschlechtsgebundene Vererbung beim Huhn","Beim Huhn sind Hähne homogametisch mit ZZ und Hennen heterogametisch mit ZW.","Hennen besitzen ZZ, Hähne ZW; das weibliche Geschlecht ist damit homogametisch.","Hähne besitzen XY, Hennen XX; das männliche Geschlecht ist damit heterogametisch.","Hennen besitzen XY, Hähne XX; das weibliche Geschlecht ist damit heterogametisch.","Die unterschiedliche Chromosomenausstattung ist für die Planung geschlechtsgebundener Kreuzungen entscheidend."],
  ["Zuchtplanung","schwer","Inzuchtkoeffizient","Der Inzuchtkoeffizient gibt an, wie wahrscheinlich beide Allele eines Genortes von derselben ursprünglichen Kopie abstammen.","Der Inzuchtkoeffizient gibt den Anteil rezessiver Merkmale an, die ein Tier während seiner Entwicklung sichtbar ausprägt.","Der Inzuchtkoeffizient gibt die Wahrscheinlichkeit an, dass zwei zufällige Tiere einer Rasse denselben Phänotyp besitzen.","Der Inzuchtkoeffizient gibt den Anteil homozygoter Eltern an, deren Nachkommen bei einer Paarung die Zuchtreife erreichen.","Gemeinsame Vorfahren erhöhen die Wahrscheinlichkeit identischer Allelkopien; vollständige Pedigrees verbessern die Schätzung."],
  ["Zuchtplanung","schwer","Erblichkeit und Selektion","Heritabilität bezieht sich auf die Varianz einer Population unter bestimmten Bedingungen, nicht auf die Unveränderlichkeit eines Tiers.","Heritabilität beschreibt den Anteil eines Einzelmerkmals, der beim betrachteten Tier durch Fütterung nicht veränderbar ist.","Heritabilität beschreibt die Wahrscheinlichkeit, mit der ein Elterntier seinen genauen Merkmalswert an Nachkommen vererbt.","Heritabilität beschreibt einen rassetypischen Wert, der bei wechselnder Haltung und Umwelt für das Merkmal erhalten bleibt.","Der Kennwert bezieht sich auf phänotypische Varianz in einer bestimmten Population unter bestimmten Bedingungen."],
  ["Eibildung","schwer","Schalenbildung","Die Kalkschale des Eis entsteht hauptsächlich im Uterusabschnitt des Legedarms.","Die Kalkschale entsteht überwiegend im Isthmus, zusammen mit den beiden Schalenhäuten.","Die Kalkschale entsteht überwiegend im Magnum, während Eiweiß um den Dotter gelagert wird.","Die Kalkschale entsteht überwiegend im Infundibulum, kurz nach der Aufnahme des Dotters.","Nach Dotteraufnahme und Eiweiß-/Schalenhautbildung verweilt das Ei lange im Uterus, wo Kalziumkarbonat abgelagert wird."],
  ["Eibildung","schwer","Cuticula des Eis","Die Cuticula bedeckt die Schale außen, verschließt Poren teilweise und erschwert so das Eindringen von Keimen.","Die Cuticula liegt zwischen den Schalenhäuten und reguliert dort den Übertritt von Wasser aus dem Eiklar.","Die Cuticula besteht aus dem inneren Kalkgerüst und bildet die Hauptreserve an Kalzium für den Embryo.","Die Cuticula bildet sich beim Abkühlen aus kondensiertem Wasser und verschließt dadurch die Schalenporen.","Unsachgemäßes Waschen oder Abrieb kann die natürliche Barriere der frisch gelegten Schale beeinträchtigen."],
  ["Tierverhalten","schwer","Federpicken","Federpicken wird durch mehrere Faktoren beeinflusst und ist nicht mit aggressivem Picken gleichzusetzen.","Federpicken ist eine Form der Rangordnungsaggression und richtet sich vorwiegend gegen Kopf und Kamm.","Federpicken entsteht durch das Erlernen von Abwehrverhalten und nimmt durch zusätzliches Scharrmaterial zu.","Federpicken entspricht der gegenseitigen Gefiederpflege; Federverluste zeigen dabei eine normale soziale Bindung.","Genetik, Aufzucht, Licht, Fütterung, Besatz, Struktur und Stress können zusammenwirken; die Ursachenanalyse muss mehrere Faktoren berücksichtigen."],
  ["Stallbeleuchtung","schwer","Photoperiode und Legebeginn","Zu frühe Lichtstimulation fördert die Geschlechtsreife, bevor die Körperentwicklung und die Reserven ausreichen.","Eine frühe Verlängerung des Lichttags fördert zunächst das Körperwachstum und verzögert dadurch den Legebeginn.","Eine Verlängerung des Lichttags beeinflusst den Legebeginn vorwiegend über die Erwärmung der unbefiederten Haut.","Eine frühe Lichtstimulation gleicht geringe Körperreserven aus, weil der Bedarf mit Eintritt der Legereife abnimmt.","Lichtprogramme werden an Alter, Entwicklung und Produktionsziel angepasst; abrupte oder unpassende Änderungen können Probleme begünstigen."]
]

const promptVariants = [
  subject => `Welche Aussage zu „${subject}“ ist richtig?`,
  subject => `Was trifft auf das Thema „${subject}“ zu?`,
  subject => `Wählen Sie die fachlich richtige Aussage zu „${subject}“.`
]

export const poultryQuizQuestions = advancedFacts.flatMap((fact, factIndex) => {
  const [topic, difficulty, subject, correct, ...rest] = fact
  const explanation = rest.pop()
  const incorrect = rest
  return promptVariants.map((createPrompt, variantIndex) => ({
    id: `poultry-${factIndex + 1}-${variantIndex + 1}`,
    factId: `poultry-${factIndex + 1}`,
    topic,
    difficulty,
    question: createPrompt(subject),
    correct,
    incorrect,
    explanation
  }))
})

function shuffled(items) {
  const result = [...items]
  for (let index = result.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1))
    ;[result[index], result[swapIndex]] = [result[swapIndex], result[index]]
  }
  return result
}

export function createPoultryQuizRound(questionCount = 10) {
  const selectedFacts = shuffled(advancedFacts.map((_, index) => index)).slice(0, questionCount)
  return selectedFacts.map(factIndex => {
    const variants = poultryQuizQuestions.filter(question => question.factId === `poultry-${factIndex + 1}`)
    const question = variants[Math.floor(Math.random() * variants.length)]
    return {
      ...question,
      answers: shuffled([question.correct, ...question.incorrect])
    }
  })
}

export const poultryQuizMeta = {
  factCount: advancedFacts.length,
  questionCount: poultryQuizQuestions.length,
  topics: [...new Set(advancedFacts.map(([topic]) => topic))]
}
