const facts = [
  ["Hühnerhaltung","leicht","Grundbedürfnisse von Hühnern","Hühner benötigen neben Futter und Wasser auch Scharrraum, Ruheplätze und Schutz.","Hühner brauchen nur einen Futterplatz.","Hühner sollten dauerhaft ohne Tageslicht leben.","Hühner benötigen grundsätzlich keine Rückzugsmöglichkeit.","Eine gute Haltung berücksichtigt Nahrung, Bewegung, Ruhe, Sozialverhalten und Sicherheit."],
  ["Hühnerhaltung","mittel","Sozialverhalten","Hühner leben in Gruppen mit einer erkennbaren Rangordnung.","Hühner sind konsequente Einzelgänger.","Eine Gruppe besitzt niemals soziale Strukturen.","Die Rangordnung wird nur durch die Gefiederfarbe bestimmt.","Die sogenannte Hackordnung beeinflusst unter anderem Zugang zu Ressourcen und Ruheplätzen."],
  ["Zwerghühner","leicht","Zwerghühner","Viele Zwerghuhnrassen benötigen trotz kleiner Körpergröße eine vollwertige, strukturierte Haltung.","Zwerghühner können dauerhaft in Transportboxen gehalten werden.","Kleine Rassen benötigen grundsätzlich keine Sitzstangen.","Zwerghühner brauchen weniger Hygiene als große Hühner.","Körpergröße ändert nichts an den grundlegenden Ansprüchen an Platz, Beschäftigung und Pflege."],
  ["Zwerghühner","schwer","Ur- und verzwergte Rassen","Es gibt ursprüngliche Zwerghuhnrassen und verkleinerte Formen großer Rassen.","Jedes Zwerghuhn ist eine junge Großrasse.","Zwerghühner entstehen ausschließlich durch knappe Fütterung.","Alle Zwerghühner gehören derselben Rasse an.","In der Rassegeflügelzucht wird zwischen Urzwergen und verzwergten Großrassen unterschieden."],
  ["Puten","leicht","Putenhaltung","Puten brauchen trockene, gut belüftete Bereiche und ausreichend Bewegungsraum.","Puten benötigen dauerhaft feuchte Einstreu.","Puten sollten ohne frisches Wasser gehalten werden.","Puten brauchen grundsätzlich keine geschützten Ruhebereiche.","Trockene Einstreu, saubere Luft und Platz sind wichtige Grundlagen der Putenhaltung."],
  ["Puten","mittel","Jungputen","Jungputen reagieren besonders empfindlich auf Nässe und Auskühlung.","Jungputen vertragen Nässe besser als Wassergeflügel.","Jungputen benötigen keine Wärmequelle.","Kühle Zugluft unterstützt grundsätzlich die Aufzucht.","Wärme, Trockenheit und ein passend eingestelltes Stallklima sind in der frühen Aufzucht entscheidend."],
  ["Wassergeflügel","leicht","Wassergeflügel","Enten und Gänse müssen ihre Köpfe zum Reinigen von Augen und Nasenöffnungen ins Wasser tauchen können.","Eine flache Tropftränke genügt immer für jede Reinigung.","Wassergeflügel darf niemals Wasser am Kopf haben.","Nur das Gefieder der Flügel darf nass werden.","Geeignete Wasserstellen unterstützen arttypische Pflege und freie Nasenöffnungen."],
  ["Wassergeflügel","mittel","Nasse Stallbereiche","Tränken für Wassergeflügel sollten so stehen, dass vernässte Einstreu begrenzt und leicht erneuert werden kann.","Tränken gehören immer direkt in das Legenest.","Dauerhaft nasse Einstreu verbessert die Fußgesundheit.","Wasserstellen sollten niemals gereinigt werden.","Eine durchdachte Tränkenzone erleichtert Hygiene und hält Ruheflächen trockener."],
  ["Enten","leicht","Entengefieder","Die Bürzeldrüse liefert ein Sekret, das Enten bei der Gefiederpflege verteilen.","Enten versiegeln ihr Gefieder mit Sand.","Das Gefieder bleibt nur durch Futterstaub wasserabweisend.","Die Bürzeldrüse dient ausschließlich der Lautbildung.","Beim Putzen verteilen Vögel das Sekret der Bürzeldrüse im Gefieder."],
  ["Enten","mittel","Laufenten","Laufenten besitzen eine auffallend aufrechte Körperhaltung.","Laufenten haben grundsätzlich keine Beine.","Laufenten bewegen sich ausschließlich schwimmend.","Laufenten sind eine Putenrasse.","Die aufrechte Haltung gehört zu den typischen Merkmalen der Laufenten."],
  ["Gänse","leicht","Gänse als Weidetiere","Gänse nutzen Gras als wichtigen Bestandteil ihrer Nahrung, benötigen aber dennoch eine ausgewogene Versorgung.","Gänse ernähren sich ausschließlich von Kieselsteinen.","Eine Weide ersetzt immer frisches Trinkwasser.","Gänse dürfen kein Grünfutter aufnehmen.","Weidegang ist wertvoll, muss aber zu Alter, Jahreszeit und Gesamtversorgung passen."],
  ["Gänse","mittel","Gänseverhalten","Gänse kommunizieren deutlich und können ihr Revier aufmerksam bewachen.","Gänse sind vollständig lautlos.","Gänse erkennen grundsätzlich keine Gruppenmitglieder.","Gänse zeigen niemals Schutzverhalten.","Ihre Wachsamkeit und Lautäußerungen sind bekannte Bestandteile des Gänseverhaltens."],
  ["Wachteln","leicht","Japanische Legewachteln","Japanische Legewachteln leben bodennah und benötigen Deckung sowie geschützte Rückzugsbereiche.","Legewachteln schlafen ausschließlich auf hohen Bäumen.","Wachteln benötigen einen tiefen Schwimmteich.","Wachteln sollten ohne Verstecke auf blankem Boden leben.","Struktur, Deckung und geeignete Bodenbereiche reduzieren Stress."],
  ["Wachteln","mittel","Schreckreaktion bei Wachteln","Wachteln können bei Schreck steil auffliegen, weshalb die Voliere sicher gestaltet sein muss.","Wachteln können anatomisch nicht auffliegen.","Eine harte, sehr niedrige Decke ist immer ideal.","Wachteln reagieren nie auf plötzliche Reize.","Eine angepasste Höhe oder nachgiebige Decke kann Verletzungen bei Schreckflügen vorbeugen."],
  ["Geflügelrassen","leicht","Rassenvielfalt","Geflügelrassen unterscheiden sich unter anderem in Größe, Form, Leistung, Verhalten und Gefieder.","Alle Geflügelrassen sehen gleich aus.","Rassen werden ausschließlich nach dem Alter unterschieden.","Die Gefiederfarbe ist das einzige Rassemerkmal.","Rassen entstanden durch unterschiedliche Nutzungsziele, Regionen und züchterische Auswahl."],
  ["Geflügelrassen","mittel","Zweinutzungsrassen","Zweinutzungsrassen wurden traditionell sowohl für Eier als auch für Fleisch gehalten.","Zweinutzungsrassen können weder Eier legen noch Fleisch ansetzen.","Der Begriff bezeichnet ausschließlich Wassergeflügel.","Zweinutzung bedeutet Haltung ohne Zuchtziel.","Der Begriff beschreibt die Verbindung zweier klassischer Nutzungsrichtungen."],
  ["Brut","leicht","Brutdauer beim Haushuhn","Hühnereier benötigen gewöhnlich etwa 21 Tage bis zum Schlupf.","Hühnereier schlüpfen gewöhnlich nach zwei Tagen.","Die Brut dauert immer exakt drei Monate.","Hühnereier benötigen grundsätzlich kein gleichmäßiges Brutklima.","Etwa drei Wochen gelten beim Haushuhn als übliche Brutdauer, kleine Abweichungen sind möglich."],
  ["Brut","mittel","Bruteier lagern","Bruteier sollten vor dem Einlegen sauber, schonend und nicht übermäßig lange gelagert werden.","Bruteier werden vor der Brut am besten tiefgefroren.","Starke Erschütterungen verbessern die Schlupfrate.","Das Alter eines Bruteis spielt keine Rolle.","Lagerdauer und -bedingungen beeinflussen die Entwicklungs- und Schlupfchancen."],
  ["Kunstbrut","leicht","Wenden bei der Kunstbrut","Regelmäßiges Wenden unterstützt die normale Entwicklung des Embryos.","Bruteier dürfen während der gesamten Brut niemals bewegt werden.","Wenden dient nur der Reinigung der Schale.","Stündliches kräftiges Schütteln ersetzt das Wenden.","Das Wenden verhindert unter anderem ein ungünstiges Anhaften des Embryos an den Eihäuten."],
  ["Kunstbrut","schwer","Schlupfphase","Kurz vor dem Schlupf wird das Wenden beendet und das Brutklima an die Schlupfphase angepasst.","Während des Schlupfs müssen Eier besonders stark geschüttelt werden.","Die Luftfeuchtigkeit ist während der gesamten Brut bedeutungslos.","Zum Schlupf werden alle Eier geöffnet.","Die letzten Bruttage unterscheiden sich organisatorisch von der vorherigen Entwicklungsphase."],
  ["Naturbrut","leicht","Glucke","Eine Glucke wärmt die Eier, wendet sie und führt später die Küken.","Eine Glucke ist ein männliches Küken.","Glucken legen während der Brut täglich besonders viele Eier.","Eine Glucke verlässt das Nest grundsätzlich niemals.","Brutverhalten umfasst Wärmen, Wenden, kurze Versorgungspausen und später die Kükenführung."],
  ["Naturbrut","mittel","Brutnest","Ein Brutnest sollte ruhig, trocken, sicher und für Kontrollen erreichbar sein.","Ein Brutnest gehört in einen dauerhaft nassen Durchgang.","Ständige Störungen verbessern den Bruterfolg.","Andere Hennen sollten jederzeit Eier dazulegen können.","Ein geschützter Bereich verringert Stress und erleichtert die Zuordnung des Geleges."],
  ["Kükenaufzucht","leicht","Wärmebedarf von Küken","Küken benötigen anfangs eine zuverlässige Wärmezone und die Möglichkeit, kühlere Bereiche aufzusuchen.","Küken brauchen ab dem Schlupf Frost.","Die gesamte Aufzuchtfläche muss immer gleich heiß sein.","Das Verhalten der Küken sagt nichts über die Temperatur aus.","Eine Temperaturzone erlaubt den Küken, ihren Aufenthaltsort selbst passend zu wählen."],
  ["Kükenaufzucht","mittel","Küken beobachten","Eng zusammengedrängte und laut piepsende Küken können auf Kälte oder Unwohlsein hinweisen.","Enges Drängen beweist immer perfekte Temperatur.","Kükenverhalten ist für die Aufzucht bedeutungslos.","Küken müssen sich ständig von der Wärmequelle entfernen.","Verteilung, Aktivität und Lautäußerungen liefern Hinweise auf das Wohlbefinden."],
  ["Stallbau","leicht","Sitzstangen","Sitzstangen sollten sicheren Halt bieten und so angeordnet sein, dass Tiere sie gut erreichen können.","Sitzstangen müssen glatt wie Glas sein.","Sitzstangen gehören direkt über Futter und Wasser.","Hühner ruhen grundsätzlich nur auf dem Stallboden.","Form, Abstand und Position beeinflussen sicheren Auf- und Abstieg sowie Hygiene."],
  ["Stallbau","mittel","Legenester","Legenester sollten ruhig, sauber und etwas abgedunkelt sein.","Legenester stehen idealerweise im lautesten Durchgang.","Nasse Einstreu fördert saubere Eier.","Ein Nest muss vollständig durchsichtig und ungeschützt sein.","Geschützte Nester werden eher angenommen und helfen, Eier sauber zu halten."],
  ["Stallklima","leicht","Lüftung","Gute Lüftung führt Feuchtigkeit und Schadgase ab, ohne dauerhafte Zugluft auf die Tiere zu richten.","Ein Stall sollte vollständig luftdicht sein.","Ammoniakgeruch ist ein Zeichen idealer Luftqualität.","Zugluft direkt auf den Ruheplätzen ist erwünscht.","Frische Luft und kontrollierter Luftaustausch gehören zu einem gesunden Stallklima."],
  ["Stallklima","mittel","Feuchtigkeit im Stall","Beschlagene Flächen und feuchte Einstreu können auf unzureichenden Luftaustausch hinweisen.","Feuchtigkeit hat keinen Einfluss auf Stallhygiene.","Je nasser die Einstreu, desto geringer der Keimdruck.","Lüften erhöht grundsätzlich immer die Feuchtigkeit.","Feuchte Bedingungen fördern Gerüche, Keime und Probleme an Füßen und Gefieder."],
  ["Stallhygiene","leicht","Einstreu","Verschmutzte oder feuchte Einstreu sollte regelmäßig entfernt und durch trockenes Material ersetzt werden.","Einstreu darf niemals kontrolliert werden.","Nasse Einstreu reinigt sich von selbst.","Kot unter Sitzplätzen verbessert das Stallklima.","Trockene, gepflegte Einstreu trägt zu Fußgesundheit und Luftqualität bei."],
  ["Stallhygiene","mittel","Reinigungsreihenfolge","Vor einer Desinfektion müssen Schmutz und organisches Material gründlich entfernt werden.","Desinfektionsmittel wirkt am besten auf dicken Kotschichten.","Reinigung nach der Desinfektion ist immer gleichwertig.","Wasser allein ersetzt jede mechanische Reinigung.","Organisches Material kann die Wirkung vieler Desinfektionsmittel deutlich verringern."],
  ["Fütterung","leicht","Alleinfutter","Ein passendes Alleinfutter ist darauf ausgelegt, den Nährstoffbedarf der jeweiligen Tier- und Altersgruppe zu decken.","Alleinfutter besteht nur aus Wasser.","Jedes Alleinfutter passt unverändert zu jedem Geflügelalter.","Alleinfutter darf keine Energie enthalten.","Küken, Jungtiere und Legetiere haben unterschiedliche Anforderungen an die Ration."],
  ["Fütterung","mittel","Körner als Ergänzung","Körner können eine Ration ergänzen, sollten ein ausgewogenes Hauptfutter aber nicht unkontrolliert verdrängen.","Nur Körner liefern immer alle benötigten Nährstoffe.","Je mehr Leckerbissen, desto ausgewogener die Ration.","Körner enthalten grundsätzlich keine Energie.","Zu viele Ergänzungen können das Verhältnis von Eiweiß, Energie, Vitaminen und Mineralstoffen verschieben."],
  ["Tränken","leicht","Frisches Trinkwasser","Geflügel benötigt jederzeit Zugang zu sauberem, frischem Trinkwasser.","Einmal wöchentliches Wasser reicht grundsätzlich aus.","Verschmutzte Tränken stärken das Immunsystem.","Wasser wird nur während der Eiablage benötigt.","Wasser ist für Verdauung, Temperaturregulation, Leistung und Gesundheit unverzichtbar."],
  ["Tränken","mittel","Tränkenhöhe","Eine passend eingestellte Tränkenhöhe kann Verschmutzung und Wasserverlust reduzieren.","Tränken müssen immer unter der Einstreu liegen.","Die Höhe hat keinerlei Einfluss auf Sauberkeit.","Tränken gehören auf die Sitzstange.","Die geeignete Höhe orientiert sich an Tiergröße und Tränkensystem."],
  ["Mineralstoffe","leicht","Kalzium","Kalzium ist unter anderem für Knochen und die Bildung stabiler Eierschalen wichtig.","Kalzium wird ausschließlich für die Gefiederfarbe benötigt.","Legehennen benötigen grundsätzlich kein Kalzium.","Kalzium ersetzt Trinkwasser.","Der Kalziumbedarf steigt besonders im Zusammenhang mit der Eischalenbildung."],
  ["Mineralstoffe","schwer","Grit und Muschelschalen","Magenkiesel unterstützen die mechanische Zerkleinerung im Muskelmagen, Muschelschalen liefern vor allem Kalzium.","Grit und Kalzium sind exakt dasselbe.","Muschelschalen dienen ausschließlich als Spielzeug.","Magenkiesel lösen sich sofort als Vitamin auf.","Unlöslicher Grit und lösliche Kalziumquellen erfüllen unterschiedliche Aufgaben."],
  ["Geflügelgesundheit","leicht","Tägliche Tierkontrolle","Eine tägliche Beobachtung hilft, Veränderungen bei Verhalten, Futteraufnahme und Kot früh zu erkennen.","Gesundheitskontrollen sind nur einmal jährlich sinnvoll.","Kranke Tiere zeigen immer sofort dasselbe Symptom.","Futteraufnahme sagt nichts über Wohlbefinden aus.","Frühe Abweichungen sind oft leichter zu erkennen, wenn der normale Bestand gut bekannt ist."],
  ["Geflügelgesundheit","mittel","Quarantäne","Neue oder zurückkehrende Tiere sollten zunächst getrennt beobachtet werden, bevor sie in den Bestand kommen.","Neue Tiere müssen sofort ohne Beobachtung eingestallt werden.","Quarantäne bedeutet gemeinsames Füttern im Hauptstall.","Eine Trennung erhöht automatisch den Krankheitsdruck.","Ein getrennter Bereich reduziert das Risiko, unbemerkte Erreger oder Parasiten einzuschleppen."],
  ["Parasiten","leicht","Ektoparasiten","Ektoparasiten leben auf dem Tier oder in seiner unmittelbaren Umgebung.","Ektoparasiten leben ausschließlich in Hühnereiern.","Ektoparasiten sind immer nützliche Darmbakterien.","Ektoparasiten können Geflügel niemals befallen.","Milben und Federlinge gehören zu bekannten äußeren Parasiten."],
  ["Parasiten","mittel","Bestandskontrolle auf Parasiten","Sitzstangenauflagen, Ritzen und Gefieder sollten regelmäßig auf Parasitenhinweise kontrolliert werden.","Parasiten sind nur bei Tageslicht auf freien Flächen zu finden.","Ritzen müssen nie kontrolliert werden.","Ein sauber wirkender Stall schließt Parasiten sicher aus.","Einige Parasiten verstecken sich tagsüber in Spalten und werden leicht übersehen."],
  ["Milben","leicht","Rote Vogelmilbe","Die Rote Vogelmilbe hält sich häufig in Stallritzen auf und sucht die Tiere vor allem nachts auf.","Die Rote Vogelmilbe lebt ausschließlich im Trinkwasser.","Sie ist immer dauerhaft auf der Feder sichtbar.","Sie ernährt sich nur von Getreide.","Ihre versteckte Lebensweise macht Kontrollen an Sitzplätzen und Ritzen besonders wichtig."],
  ["Milben","schwer","Milbenbekämpfung","Eine wirksame Bekämpfung muss Tierumgebung, Entwicklungsstadien und zugelassene Maßnahmen berücksichtigen.","Einmaliges Fegen beseitigt jeden Befall sicher.","Beliebige Haushaltschemikalien sind am Tier geeignet.","Nur sichtbare erwachsene Milben müssen beachtet werden.","Wiederholte Kontrolle und ein abgestimmtes Vorgehen sind wegen des Lebenszyklus wichtig."],
  ["Würmer","leicht","Endoparasiten","Würmer können den Verdauungstrakt oder andere Organe des Geflügels belasten.","Würmer leben ausschließlich auf Federspitzen.","Jeder Wurmbefall ist mit bloßem Auge sofort sichtbar.","Würmer verbessern grundsätzlich die Futterverwertung.","Je nach Art und Befallsstärke können Leistung, Gewicht und Allgemeinzustand leiden."],
  ["Würmer","mittel","Kotuntersuchung","Eine Kotuntersuchung kann Hinweise auf Wurmeier und die Notwendigkeit gezielter Maßnahmen liefern.","Entwurmung sollte immer ohne jeden Befund täglich erfolgen.","Kotproben enthalten nie Informationen über Parasiten.","Nur die Gefiederfarbe entscheidet über eine Behandlung.","Diagnostik hilft, Behandlungen fachlich zu begründen und unnötigen Einsatz zu vermeiden."],
  ["Krankheiten","leicht","Kranke Tiere separieren","Ein auffälliges Tier sollte geschützt untergebracht und fachlich beurteilt werden, ohne die Biosicherheit zu vernachlässigen.","Kranke Tiere gehören sofort in jede fremde Gruppe.","Auffälligkeiten sollten grundsätzlich ignoriert werden.","Ein krankes Tier benötigt niemals Wasser.","Eine vorübergehende Trennung erleichtert Beobachtung und kann Kontakte reduzieren."],
  ["Krankheiten","mittel","Antibiotika","Antibiotika wirken gegen bestimmte bakterielle Infektionen, nicht gegen Viren.","Antibiotika wirken zuverlässig gegen jedes Virus.","Antibiotika sind ein Futtermittel ohne Wartezeiten.","Jede Erkrankung erfordert automatisch dasselbe Antibiotikum.","Diagnose, tierärztliche Anweisung und verantwortungsvoller Einsatz sind entscheidend."],
  ["Newcastle-Krankheit","leicht","Newcastle-Krankheit","Newcastle ist eine ansteckende Viruserkrankung des Geflügels.","Newcastle ist ausschließlich ein Mineralstoffmangel.","Newcastle betrifft nur Stallgebäude.","Newcastle ist eine Gefiederfarbe.","Die Krankheit kann sich zwischen Beständen verbreiten und erfordert konsequente Vorsorge."],
  ["Newcastle-Krankheit","mittel","Newcastle-Vorsorge","Regelmäßige Impfungen sind ein zentraler Baustein zum Schutz gegen Newcastle.","Nur eine saubere Tränke ersetzt jede Impfung.","Eine Impfung ist erst nach einem Ausbruch sinnvoll.","Newcastle kann nicht vorbeugend berücksichtigt werden.","Ein planmäßig aufgebauter und aufgefrischter Impfschutz reduziert das Erkrankungsrisiko."],
  ["Impfungen","leicht","Impfschutz","Impfungen bereiten das Immunsystem auf den Kontakt mit bestimmten Erregern vor.","Impfungen ersetzen Futter und Wasser.","Jede Impfung wirkt automatisch lebenslang.","Impfungen verändern nur die Federfarbe.","Die Immunantwort benötigt Zeit und muss je nach Impfstoff wieder aufgefrischt werden."],
  ["Impfungen","mittel","Impfstoffhandhabung","Impfstoffe müssen nach den fachlichen Vorgaben gelagert, vorbereitet und angewendet werden.","Impfstoffe können beliebig erhitzt werden.","Lagerbedingungen haben keinen Einfluss auf die Wirksamkeit.","Geöffneter Impfstoff ist unbegrenzt haltbar.","Temperatur, Zeit und Anwendung beeinflussen die Qualität einer Impfung."],
  ["Biosicherheit","leicht","Saubere Stallkleidung","Eigene Schuhe und Kleidung für den Stall können die Verschleppung von Erregern reduzieren.","Stallschuhe sollten in möglichst vielen fremden Beständen getragen werden.","Schuhsohlen können keine Verschmutzung übertragen.","Kleidung spielt für Biosicherheit nie eine Rolle.","Organisches Material an Schuhen und Geräten kann Krankheitserreger weitertragen."],
  ["Biosicherheit","mittel","Besucher und Geräte","Kontakte, Besucher und gemeinsam genutzte Geräte sollten bewusst in das Hygienekonzept einbezogen werden.","Geliehene Geräte müssen nie gereinigt werden.","Viele unnötige Bestandskontakte senken jedes Risiko.","Biosicherheit betrifft ausschließlich das Trinkwasser.","Kontrollierte Wege und gereinigte Ausrüstung verringern mögliche Eintragswege."],
  ["Tierkennzeichnung","leicht","Kennzeichnung","Eine eindeutige Kennzeichnung hilft, Tiere und Zuchtinformationen nachvollziehbar zuzuordnen.","Kennzeichnung dient nur der Dekoration.","Jede Kennzeichnung ist automatisch eine Impfung.","Kennzeichnung macht Aufzeichnungen überflüssig.","Zuordnung ist für Abstammung, Alter, Zuchtplanung und Bestandsführung hilfreich."],
  ["Tierkennzeichnung","mittel","Ringe kontrollieren","Fußringe müssen zur Tiergröße passen und regelmäßig auf korrekten Sitz kontrolliert werden.","Ein zu enger Ring wächst gefahrlos mit.","Ringe dürfen niemals angesehen werden.","Jede Tierart trägt dieselbe Ringgröße.","Wachstum, Verschmutzung oder Verletzungen können Probleme verursachen."],
  ["Bundesringe","leicht","Geschlossene Bundesringe","Geschlossene Ringe werden Jungtieren in einem begrenzten Altersfenster über den Fuß gestreift.","Geschlossene Ringe werden bei Alttieren aufgeschnitten und geklebt.","Bundesringe sind ausschließlich Futtermarken.","Jeder Ring kann beliebig oft zwischen Tieren getauscht werden.","Nach dem Wachstum lässt sich ein passender geschlossener Ring nicht zerstörungsfrei abnehmen."],
  ["Bundesringe","schwer","Informationen auf Bundesringen","Bundesringe ermöglichen unter anderem die Zuordnung von Jahrgang und individueller Ringnummer.","Bundesringe zeigen automatisch jede Impfung an.","Auf einem Bundesring steht immer das aktuelle Gewicht.","Bundesringe ersetzen jeden Abstammungsnachweis vollständig.","Die Ringangaben unterstützen die Identifikation, müssen aber mit Zuchtaufzeichnungen verbunden werden."],
  ["Rassegeflügelzucht","leicht","Zuchtziel","Ein Zuchtziel verbindet Gesundheit, Vitalität und rassetypische Merkmale.","Zuchtziele berücksichtigen ausschließlich die höchste Körpermasse.","Gesundheit spielt in der Zucht keine Rolle.","Ein Zuchtziel ändert sich täglich für jedes Tier.","Verantwortungsvolle Auswahl achtet auf Funktion, Typ und robuste Nachzucht."],
  ["Rassegeflügelzucht","mittel","Zuchtbuch","Ein Zuchtbuch hilft, Abstammung, Schlupf, Leistung und Beobachtungen festzuhalten.","Ein Zuchtbuch enthält nur Futtermittelpreise.","Abstammung lässt sich ohne Kennzeichnung immer sicher merken.","Aufzeichnungen verhindern jede genetische Vielfalt.","Systematische Daten verbessern Nachvollziehbarkeit und Paarungsplanung."],
  ["Vererbung","leicht","Gene","Nachkommen erhalten Erbanlagen von beiden Elternteilen.","Nur der Vater vererbt Merkmale.","Fütterung ersetzt sämtliche Gene.","Erbanlagen entstehen erst nach dem Schlupf.","Die sichtbare Ausprägung entsteht aus Erbanlagen und Umwelteinflüssen."],
  ["Vererbung","schwer","Rezessive Merkmale","Ein rezessives Merkmal kann verdeckt getragen werden und erst bei passender Genkombination sichtbar werden.","Rezessiv bedeutet immer tödlich.","Rezessive Anlagen werden niemals vererbt.","Ein verdecktes Merkmal ist automatisch verschwunden.","Trägertiere können eine Anlage weitergeben, ohne sie selbst sichtbar zu zeigen."],
  ["Farben","mittel","Gefiederfarben","Gefiederfarben entstehen durch genetisch gesteuerte Pigmente und Strukturwirkungen.","Jede Gefiederfarbe wird nur durch das Futter bestimmt.","Alle Küken behalten exakt dieselbe Dunenfarbe als Erwachsenengefieder.","Farbe hat keinerlei genetische Grundlage.","Mehrere Gene können Grundfarbe, Zeichnung, Verdünnung und Glanz beeinflussen."],
  ["Farben","schwer","Farbvererbung","Bei manchen Farbmerkmalen ist die Vererbung geschlechtsgebunden.","Alle Farbmerkmale werden ausschließlich über die Mutter vererbt.","Geschlechtsgebundene Vererbung bedeutet zufällige Farbe ohne Gene.","Jedes Farbmerkmal folgt demselben einfachen Erbgang.","Die Lage eines Gens auf einem Geschlechtschromosom kann Paarungsergebnisse beeinflussen."],
  ["Zuchtziele","leicht","Gesunde Zuchttiere","Vitale, gesunde und fortpflanzungsfähige Tiere sind eine wichtige Grundlage der Zucht.","Nur ein auffälliges Einzelmerkmal zählt.","Kranke Tiere verbessern automatisch jede Linie.","Beweglichkeit ist für Zuchttiere bedeutungslos.","Äußere Merkmale dürfen nicht losgelöst von Gesundheit und Funktion betrachtet werden."],
  ["Zuchtziele","mittel","Auswahl über Generationen","Züchterischer Fortschritt entsteht durch planmäßige Auswahl und verlässliche Aufzeichnungen über mehrere Generationen.","Ein einziges Tier verändert sofort die gesamte Rasse.","Zuchtplanung benötigt keine Abstammungsdaten.","Zufallspaarungen liefern immer dasselbe Ergebnis.","Vererbung zeigt sich in Familien und Nachzucht, nicht nur im Erscheinungsbild eines Einzeltieres."],
  ["Ausstellungen","leicht","Ausstellungsvorbereitung","Tiere sollten gesund, sauber, ruhig gewöhnt und sicher transportiert werden.","Kranke Tiere gehören zur Gewöhnung auf jede Ausstellung.","Vorbereitung beginnt erst nach der Bewertung.","Transportbehälter benötigen keine Luftzufuhr.","Gesundheit, Pflege und stressarme Gewöhnung sind wichtiger als kurzfristige Kosmetik."],
  ["Ausstellungen","mittel","Transport zur Ausstellung","Transportkisten müssen zur Tiergröße passen, belüftet und sicher verschlossen sein.","Geflügel wird am sichersten lose im Fahrzeug transportiert.","Je enger und dunkler ohne Luft, desto besser.","Eine beschädigte Kiste erhöht die Sicherheit.","Sichere Behälter schützen Tiere, Menschen und andere Verkehrsteilnehmer."],
  ["Bewertung","leicht","Rassegeflügelbewertung","Bei der Bewertung werden Tiere mit dem geltenden Rassestandard verglichen.","Bewertet wird ausschließlich der Name des Züchters.","Jede Rasse besitzt genau dieselbe Idealform.","Nur das Körpergewicht entscheidet.","Typ, Form, Haltung, Gefieder und weitere Merkmale werden rassespezifisch betrachtet."],
  ["Bewertung","mittel","Bewertungskarte","Eine Bewertungskarte dokumentiert Vorzüge, Wünsche und gegebenenfalls Mängel eines ausgestellten Tieres.","Die Bewertungskarte ist ein Impfpass.","Sie enthält niemals Hinweise zum Tier.","Sie ersetzt dauerhaft jede Zuchtaufzeichnung.","Die Hinweise können Züchterinnen und Züchtern bei der weiteren Auswahl helfen."],
  ["Vereinswesen","leicht","Geflügelzuchtverein","Ein Verein ermöglicht Austausch, gemeinsame Termine und die Weitergabe praktischer Erfahrung.","Ein Verein dient ausschließlich dem Verkauf von Futter.","Vereinsarbeit findet grundsätzlich ohne Mitglieder statt.","Vereine dürfen kein Wissen vermitteln.","Gemeinschaftliche Organisation unterstützt Zucht, Tiergesundheit und Nachwuchsarbeit."],
  ["Vereinswesen","mittel","Ehrenamt","Viele Angebote eines Geflügelzuchtvereins beruhen auf ehrenamtlichem Engagement.","Ehrenamt bedeutet automatisch bezahlte Vollzeitarbeit.","Gemeinsame Termine organisieren sich ohne Mitarbeit.","Ehrenamt ist nur eine Geflügelrasse.","Zeit, Fachwissen und verlässliche Zusammenarbeit machen Vereinsangebote möglich."],
  ["Geschichte der Geflügelzucht","mittel","Domestikation des Haushuhns","Das Haushuhn stammt wesentlich vom südasiatischen Bankivahuhn ab.","Das Haushuhn stammt vom europäischen Höckerschwan ab.","Haushühner wurden erst im 20. Jahrhundert domestiziert.","Das Haushuhn ist eine Form der Hauskatze.","Über lange Zeit entstanden aus domestizierten Hühnern zahlreiche regionale Rassen und Schläge."],
  ["Geschichte der Geflügelzucht","schwer","Entstehung von Rassen","Viele Geflügelrassen wurden durch regionale Bedingungen und unterschiedliche Nutzungsziele geprägt.","Alle Rassen entstanden gleichzeitig an einem Ort.","Regionale Haltungsbedingungen hatten nie Einfluss.","Rassen existieren unverändert seit der Kreidezeit.","Selektion auf Eier, Fleisch, Robustheit oder Erscheinungsbild formte die heutige Vielfalt."],
  ["Allgemeines Geflügelwissen","leicht","Muskelmagen","Der Muskelmagen hilft Vögeln, Nahrung mechanisch zu zerkleinern.","Der Muskelmagen dient ausschließlich dem Fliegen.","Geflügel besitzt keinen Verdauungstrakt.","Der Muskelmagen produziert Eierschalen.","Magenkiesel können die Zerkleinerung harter Futterbestandteile unterstützen."],
  ["Allgemeines Geflügelwissen","mittel","Kloake","Bei Vögeln münden Verdauungs-, Harn- und Geschlechtswege in die Kloake.","Die Kloake ist eine Feder am Flügel.","Die Kloake dient nur der Lautbildung.","Vögel besitzen drei vollständig getrennte äußere Öffnungen wie Säugetiere.","Die Kloake ist eine gemeinsame Körperöffnung mit mehreren Funktionen."],
  ["Allgemeines Geflügelwissen","leicht","Staubbad","Ein Staubbad unterstützt Gefiederpflege und arttypisches Verhalten.","Staubbäder dienen ausschließlich der Eiablage.","Geflügel darf niemals in trockenem Material scharren.","Ein Staubbad ersetzt Trinkwasser.","Trockene, lockere Substrate ermöglichen das typische Baden und Putzen."],
  ["Allgemeines Geflügelwissen","mittel","Mauser","Während der Mauser wird altes Gefieder ersetzt und die Legeleistung kann vorübergehend sinken.","Mauser bedeutet ausschließlich eine ansteckende Krankheit.","Federn werden nur einmal im Leben erneuert.","Während der Mauser steigt die Legeleistung immer zwingend.","Federneubildung benötigt Nährstoffe und kann den Organismus sichtbar beanspruchen."]
]

const advancedFacts = [
  ["Brutbiologie","schwer","Luftkammer und Schlupf","Die Luftkammer vergrößert sich während der Brut durch Wasserverlust und dient dem Küken beim inneren Anpicken als erste Luftreserve.","Die Luftkammer versorgt den Embryo während der gesamten Brut aktiv mit Futter.","Eine möglichst kleine Luftkammer am Schlupftag beweist stets optimale Brutbedingungen.","Die Luftkammer entsteht erst, wenn das Küken die Kalkschale von außen anpickt.","Ihre Entwicklung erlaubt Rückschlüsse auf den Feuchtigkeitsverlust; vor dem äußeren Schlupf nutzt das Küken die Luft in der Kammer."],
  ["Kunstbrut","schwer","Gewichtsverlust von Bruteiern","Der Gewichtsverlust einer repräsentativen Eierstichprobe kann genutzt werden, um die Feuchteführung während der Brut zu beurteilen.","Bruteier sollten bis zum Schlupf keinerlei Gewicht verlieren.","Gewichtsverlust zeigt ausschließlich eine bakterielle Infektion an.","Nur die Bruttemperatur, niemals die Luftfeuchte, beeinflusst den Wasserverlust.","Wasser diffundiert durch die Schale; ein plausibler Verlauf hilft, Abweichungen der Feuchteführung zu erkennen."],
  ["Kunstbrut","schwer","Temperaturmessung im Brüter","Die Aussage eines Temperaturwerts hängt auch von Messort, Fühlerhöhe, Luftführung und Brüterbauart ab.","Jeder Messpunkt im Brüter zeigt unter allen Bedingungen exakt dieselbe Temperatur.","Ein Thermometer auf dem Boden misst immer die Temperatur auf Embryohöhe.","Umluft- und Flächenbrüter werden unabhängig vom Messort identisch beurteilt.","Temperaturschichtung und Luftbewegung machen eine zur Bauart passende Messposition erforderlich."],
  ["Bruteier","schwer","Porosität der Eischale","Schalenporen ermöglichen den Austausch von Sauerstoff, Kohlendioxid und Wasserdampf zwischen Ei und Umgebung.","Eine intakte Eischale ist vollständig gasdicht.","Schalenporen transportieren ausschließlich Kalzium in den Embryo.","Der Gasaustausch beginnt erst nach dem äußeren Anpicken.","Der Embryo ist auf Diffusion durch Schale und Schalenhäute angewiesen; zugleich beeinflusst die Porosität den Wasserverlust."],
  ["Bruteier","schwer","Hagelschnüre","Hagelschnüre stabilisieren den Dotter im Eiklar und helfen, die Keimscheibe in günstiger Lage zu halten.","Hagelschnüre verbinden den Embryo direkt mit der Luftkammer.","Hagelschnüre sind beginnende Blutgefäße des Embryos.","Sie entstehen ausschließlich durch falsches Wenden im Brüter.","Die spiraligen Eiweißstrukturen wirken als elastische Aufhängung des Dotters."],
  ["Kükenaufzucht","schwer","Beurteilung der Wärmezone","Die Verteilung und das Verhalten der Küken sind aussagekräftiger als ein einzelner Temperaturwert fern der Tiere.","Küken müssen unabhängig von ihrem Verhalten stets direkt unter der Wärmequelle sitzen.","Gleichmäßiges Meiden der Wärmequelle beweist immer eine zu niedrige Temperatur.","Lautäußerungen und Verteilung haben keinen Bezug zum Stallklima.","Zugluft, Bodenwärme und Strahlungsbereich können das Empfinden verändern; deshalb wird der Messwert mit Tierbeobachtung kombiniert."],
  ["Fütterung","schwer","Rohprotein und Aminosäuren","Ein hoher Rohproteingehalt garantiert nicht automatisch eine bedarfsgerechte Versorgung mit essenziellen Aminosäuren.","Rohprotein und jede einzelne Aminosäure sind ernährungsphysiologisch identisch.","Legehennen können alle essenziellen Aminosäuren unbegrenzt selbst bilden.","Die Aminosäurenzusammensetzung ist nur für die Gefiederfarbe relevant.","Entscheidend sind Verdaulichkeit und Aminosäurenmuster; limitierende Aminosäuren können die Nutzung des übrigen Proteins begrenzen."],
  ["Fütterung","schwer","Kalziumversorgung von Legehennen","Partikuläre Kalziumquellen können durch längeren Verbleib im Muskelmagen die nächtliche Schalenbildung unterstützen.","Kalzium wird für die Eischale ausschließlich am Vormittag benötigt.","Sehr feines Kalzium verbleibt grundsätzlich länger im Muskelmagen als grobe Partikel.","Eine hohe Kalziumgabe ersetzt Phosphor und Vitamin D vollständig.","Korngröße, Aufnahmezeit und Gesamtversorgung beeinflussen die Verfügbarkeit während der Schalenbildung."],
  ["Fütterung","schwer","Nicht-Stärke-Polysaccharide","Bestimmte lösliche Nicht-Stärke-Polysaccharide können die Viskosität des Darminhalts erhöhen und dadurch die Nährstoffverwertung beeinflussen.","Nicht-Stärke-Polysaccharide werden vollständig wie Glukose aufgenommen.","Sie beeinflussen ausschließlich die Farbe des Futters.","Eine höhere Darmviskosität verbessert grundsätzlich jede Verdauungsleistung.","Je nach Getreideart und Ration können viskose Faserfraktionen Verdauung und Kotbeschaffenheit verändern."],
  ["Verdauung","schwer","Funktion der Blinddärme","In den paarigen Blinddärmen findet mikrobielle Fermentation statt; ihre Bedeutung hängt unter anderem von Futter und Tierart ab.","Die Blinddärme produzieren die Kalkschale des Eis.","Geflügel besitzt nur einen Blinddarm ohne mikrobielle Aktivität.","Blinddärme dienen ausschließlich als Speicher für Magenkiesel.","Die Caeca beherbergen Mikroorganismen und tragen zur Fermentation bestimmter Substrate bei."],
  ["Stallklima","schwer","Ammoniak im Stall","Ammoniak entsteht vor allem beim mikrobiellen Abbau stickstoffhaltiger Ausscheidungen und wird durch Feuchte, Temperatur und pH beeinflusst.","Ammoniak entsteht ausschließlich durch ausgeatmetes Kohlendioxid.","Trockene Einstreu und Lüftung erhöhen die Ammoniakfreisetzung grundsätzlich.","Ammoniak ist geruchlos und für Schleimhäute bedeutungslos.","Feuchte Einstreu und ungünstige Lüftung fördern die Belastung; Schleimhäute und Atemwege können beeinträchtigt werden."],
  ["Stallklima","schwer","Relative Luftfeuchte","Relative Luftfeuchte beschreibt den Sättigungsgrad der Luft und ändert sich bei gleicher Wasserdampfmenge mit der Temperatur.","Relative Luftfeuchte ist unabhängig von der Lufttemperatur.","Warme Luft kann grundsätzlich weniger Wasserdampf aufnehmen als kalte.","Hundert Prozent relative Feuchte bedeutet, dass der Stall vollständig mit Wasser gefüllt ist.","Wird Luft abgekühlt, kann die relative Feuchte bis zum Taupunkt steigen, obwohl keine Feuchte hinzugekommen ist."],
  ["Biosicherheit","schwer","Rein-Raus-Prinzip","Beim Rein-Raus-Prinzip werden Tiergruppen möglichst gemeinsam eingestallt und der Bereich zwischen Gruppen vollständig gereinigt und desinfiziert.","Rein-Raus bedeutet täglichen Austausch einzelner Tiere zwischen allen Gruppen.","Das Prinzip ersetzt Quarantäne und Hygieneschleusen in jedem Fall.","Eine Leerzeit ist mit dem Rein-Raus-Prinzip unvereinbar.","Das Unterbrechen von Infektionsketten gelingt besser, wenn Altersgruppen nicht fortlaufend vermischt und Bereiche gruppenweise aufbereitet werden."],
  ["Biosicherheit","schwer","Desinfektionswirksamkeit","Konzentration, Einwirkzeit, Temperatur, Oberflächenzustand und organische Belastung beeinflussen die Wirkung eines Desinfektionsmittels.","Eine höhere Konzentration verkürzt jede notwendige Einwirkzeit beliebig.","Organisches Material verbessert grundsätzlich die Desinfektion.","Die Zulassung und das Erregerspektrum eines Mittels sind bedeutungslos.","Desinfektion setzt Reinigung und die Einhaltung der produktspezifischen Anwendungsbedingungen voraus."],
  ["Impfungen","schwer","Trinkwasserimpfung","Bei einer Trinkwasserimpfung müssen Impfstofflösung, Leitungssystem und Wasseraufnahme so abgestimmt sein, dass die Tiere innerhalb des vorgesehenen Zeitfensters eine wirksame Dosis aufnehmen.","Chlorhaltiges Wasser verbessert jeden Lebendimpfstoff.","Die Lösung darf über viele Tage verteilt angeboten werden.","Eine ungleichmäßige Wasseraufnahme hat keinen Einfluss auf den Impferfolg.","Wasserqualität, Stabilisierung, Verteilung und zügige Aufnahme sind für eine gleichmäßige Immunisierung entscheidend."],
  ["Impfungen","schwer","Maternale Antikörper","Maternale Antikörper können Jungtiere vorübergehend schützen, aber bei manchen Impfstoffen auch die aktive Immunantwort beeinflussen.","Maternale Antikörper bleiben lebenslang in unveränderter Höhe bestehen.","Sie werden ausschließlich vom Vater übertragen.","Sie machen jede spätere aktive Immunisierung grundsätzlich unmöglich.","Die Antikörperspiegel fallen nach dem Schlupf ab; Impfzeitpunkt und Impfstoff müssen zur jeweiligen Situation passen."],
  ["Newcastle-Krankheit","schwer","Impfschutz und Infektion","Eine Impfung kann Erkrankung und Ausscheidung deutlich reduzieren, garantiert aber nicht unter allen Bedingungen eine sterile Immunität.","Geimpfte Tiere können unter keinen Umständen mit dem Virus in Kontakt kommen.","Eine Impfung beseitigt das Virus automatisch aus jedem bereits infizierten Bestand.","Biosicherheit ist nach einer Impfung überflüssig.","Impfschutz, Expositionsdosis, Impfstoffanwendung und Immunstatus beeinflussen den Verlauf; Biosicherheit bleibt erforderlich."],
  ["Geflügelgesundheit","schwer","Bestandsdiagnostik","Für die Bestandsdiagnostik sind Verlauf, Tiergruppe, klinische Befunde, Sektion und geeignete Laborproben gemeinsam aussagekräftiger als ein Einzelsymptom.","Ein einzelnes unspezifisches Symptom beweist immer eine bestimmte Krankheit.","Laborproben sind unabhängig von Entnahmezeit und Lagerung gleichwertig.","Bestandsdaten erschweren grundsätzlich jede Diagnose.","Viele Geflügelkrankheiten zeigen ähnliche Symptome; Kontext und fachgerechte Proben erhöhen die diagnostische Sicherheit."],
  ["Parasiten","schwer","Präpatenzzeit bei Endoparasiten","Als Präpatenzzeit gilt die Zeit von der Infektion bis zum ersten nachweisbaren Auftreten von Fortpflanzungsprodukten des Parasiten.","Präpatenzzeit bezeichnet ausschließlich die Lebensdauer eines erwachsenen Huhns.","Während der Präpatenzzeit ist eine Infektion grundsätzlich ausgeschlossen.","Der Begriff beschreibt die Einwirkzeit eines Desinfektionsmittels.","Ein Tier kann bereits infiziert sein, obwohl beispielsweise noch keine Eier im Kot nachweisbar sind."],
  ["Kokzidien","schwer","Wirtsspezifität von Eimerien","Viele Eimeria-Arten des Huhns sind wirts- und organspezifisch und befallen bevorzugt bestimmte Darmabschnitte.","Alle Kokzidienarten befallen jede Tierart und jedes Organ identisch.","Eimerien vermehren sich ausschließlich in der Einstreu, niemals im Tier.","Der betroffene Darmabschnitt ist diagnostisch ohne Bedeutung.","Art, Läsionsort und Entwicklungszyklus stehen in engem Zusammenhang und unterstützen die Einordnung eines Befalls."],
  ["Milben","schwer","Rote Vogelmilbe und Lebenszyklus","Da ein großer Teil der Population abseits des Wirtes in Ritzen lebt, reicht die Behandlung sichtbarer Milben auf dem Tier meist nicht aus.","Alle Entwicklungsstadien leben ständig tief im Blutkreislauf des Huhns.","Die Milbe ist nur während der Mittagszeit aktiv und sichtbar.","Eier und Rückzugsorte haben für die Bekämpfung keine Bedeutung.","Umgebung, Verstecke, Wiederholung und zugelassene Maßnahmen müssen in ein abgestimmtes Konzept einbezogen werden."],
  ["Genetik","schwer","Testpaarung","Eine Testpaarung kann helfen zu klären, ob ein phänotypisch dominantes Tier eine rezessive Anlage verdeckt trägt.","Eine Testpaarung verändert nachträglich den Genotyp des Elterntiers.","Dazu wird das Tier ausschließlich mit einem homozygot dominanten Partner verpaart.","Aus einem einzigen Nachkommen lässt sich jeder Genotyp immer sicher ableiten.","Bei Paarung mit einem passend homozygot rezessiven Tier können rezessive Nachkommen auf einen heterozygoten Elternteil hinweisen."],
  ["Genetik","schwer","Unvollständige Dominanz","Bei unvollständiger Dominanz zeigt der heterozygote Phänotyp eine Zwischen- oder eigene Ausprägung gegenüber beiden Homozygoten.","Der heterozygote Phänotyp entspricht zwingend vollständig dem dominanten Homozygoten.","Unvollständige Dominanz bedeutet, dass keine Allele vererbt werden.","Sie tritt ausschließlich bei geschlechtsgebundenen Merkmalen auf.","Die Ausprägung erlaubt häufig eine phänotypische Unterscheidung aller drei Genotypklassen."],
  ["Genetik","schwer","Geschlechtsgebundene Vererbung beim Huhn","Beim Huhn sind Hähne homogametisch ZZ und Hennen heterogametisch ZW.","Hennen besitzen ZZ und Hähne ZW.","Beide Geschlechter besitzen ausschließlich das Chromosomenpaar XX.","Geschlechtschromosomen beeinflussen beim Geflügel niemals Merkmale.","Die unterschiedliche Chromosomenausstattung ist für die Planung geschlechtsgebundener Kreuzungen entscheidend."],
  ["Zuchtplanung","schwer","Inzuchtkoeffizient","Der Inzuchtkoeffizient beschreibt die Wahrscheinlichkeit, dass zwei Allele an einem Genort abstammungsidentisch sind.","Er gibt ausschließlich den Anteil schwarzer Tiere in einer Linie an.","Er ist bei jeder Verpaarung innerhalb einer Rasse automatisch null.","Er lässt sich ohne Abstammungsbezug allein aus dem Körpergewicht bestimmen.","Gemeinsame Vorfahren erhöhen die Wahrscheinlichkeit identischer Allelkopien; vollständige Pedigrees verbessern die Schätzung."],
  ["Zuchtplanung","schwer","Erblichkeit und Selektion","Eine hohe Heritabilität eines Merkmals in einer Population bedeutet nicht, dass das Merkmal bei einem Einzeltier unveränderlich ist.","Heritabilität beschreibt den genetischen Anteil eines einzelnen Tieres in Prozent.","Ein hoher Wert beweist, dass Umweltbedingungen keine Rolle spielen.","Heritabilität ist für jede Population und Umwelt immer identisch.","Der Kennwert bezieht sich auf phänotypische Varianz in einer bestimmten Population unter bestimmten Bedingungen."],
  ["Eibildung","schwer","Schalenbildung","Der überwiegende Teil der Kalkschale wird im Uterusabschnitt des Legedarms gebildet.","Die Kalkschale entsteht vollständig im Eierstock.","Die Schale wird erst nach dem Legen an der Luft gebildet.","Der Muskelmagen presst die Kalkschale um den Dotter.","Nach Dotteraufnahme und Eiweiß-/Schalenhautbildung verweilt das Ei lange im Uterus, wo Kalziumkarbonat abgelagert wird."],
  ["Eibildung","schwer","Cuticula des Eis","Die Cuticula ist eine äußere Schutzschicht, die Schalenporen teilweise abdeckt und den Keimeintritt erschwert.","Die Cuticula ist der gelbe Kern des Dotters.","Kräftiges Scheuern verbessert die Cuticula dauerhaft.","Sie wird ausschließlich im Brüter künstlich erzeugt.","Unsachgemäßes Waschen oder Abrieb kann die natürliche Barriere der frisch gelegten Schale beeinträchtigen."],
  ["Tierverhalten","schwer","Federpicken","Federpicken ist ein multifaktorielles Verhaltensproblem und nicht mit aggressivem Picken allein gleichzusetzen.","Federpicken wird ausschließlich durch einen einzigen Parasiten verursacht.","Mehr Beschäftigung verschlechtert Federpicken grundsätzlich.","Betroffene Tiere zeigen immer gleichzeitig eine bakterielle Erkrankung.","Genetik, Aufzucht, Licht, Fütterung, Besatz, Struktur und Stress können zusammenwirken; die Ursachenanalyse muss mehrere Faktoren berücksichtigen."],
  ["Stallbeleuchtung","schwer","Photoperiode und Legebeginn","Eine zu frühe Lichtstimulation kann die Geschlechtsreife fördern, obwohl Körperentwicklung und Reserven noch nicht ausreichend sind.","Die Tageslänge hat beim Geflügel keinerlei Einfluss auf die Fortpflanzungsphysiologie.","Mehr Lichtstunden erhöhen unbegrenzt und ohne Nebenwirkungen jede Leistung.","Nur die Lichtfarbe, niemals die Dauer, beeinflusst den Legebeginn.","Lichtprogramme werden an Alter, Entwicklung und Produktionsziel angepasst; abrupte oder unpassende Änderungen können Probleme begünstigen."]
]

const promptVariants = [
  subject => `Welche Aussage zu „${subject}“ ist richtig?`,
  subject => `Was trifft auf das Thema „${subject}“ zu?`,
  subject => `Wählen Sie die fachlich richtige Aussage zu „${subject}“.`
]

export const poultryQuizQuestions = advancedFacts.flatMap((fact, factIndex) => {
  const [topic, difficulty, subject, correct, ...rest] = fact
  const explanation = rest.pop()
  const incorrect = rest
  return promptVariants.map((createPrompt, variantIndex) => ({
    id: `poultry-${factIndex + 1}-${variantIndex + 1}`,
    factId: `poultry-${factIndex + 1}`,
    topic,
    difficulty,
    question: createPrompt(subject),
    correct,
    incorrect,
    explanation
  }))
})

function shuffled(items) {
  const result = [...items]
  for (let index = result.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1))
    ;[result[index], result[swapIndex]] = [result[swapIndex], result[index]]
  }
  return result
}

export function createPoultryQuizRound(questionCount = 10) {
  const selectedFacts = shuffled(advancedFacts.map((_, index) => index)).slice(0, questionCount)
  return selectedFacts.map(factIndex => {
    const variants = poultryQuizQuestions.filter(question => question.factId === `poultry-${factIndex + 1}`)
    const question = variants[Math.floor(Math.random() * variants.length)]
    return {
      ...question,
      answers: shuffled([question.correct, ...question.incorrect])
    }
  })
}

export const poultryQuizMeta = {
  factCount: advancedFacts.length,
  questionCount: poultryQuizQuestions.length,
  topics: [...new Set(advancedFacts.map(([topic]) => topic))]
}
